### ISSUE TITLE
ConditionalField attribute doesn't hide Arrays

### ISSUE THREAD

**Issue by nipunasudha** [Deadcows/MyBox#10]
ConditionalField attribute doesn't hide Arrays for built-in types and custom types. Here is what I tried.

        public bool showAges;
        [ConditionalField(nameof(showAges))] public int[] ageArray;

![image](https://user-images.githubusercontent.com/17500323/54875396-644bf700-4e24-11e9-966e-8fce52c7ca63.png)

**Comment by Deadcows** [comment]
Unfortunately that's how AttributeDrawer works with with arrays in unity :( It's not applied to array property but instead to every array element. So with empty arrays we're unable to run custom code with property drawers. 
I don't know how to achieve this for now. 

I'll leave this issue opened as a reminder though. Maybe new unity UI called UI Elements will allow somehow handle this

**Comment by Deadcows** [comment]
This one now in my TODO list. I'll close this issue for now

**Comment by skullthug** [comment]
Came to post about this but noticed this had already been reported. Any ideas when this might be added?
Otherwise this thing is perfection.

**Comment by Deadcows** [comment]
Yeah, I've got an idea for that case. Instead of PropertyDrawer for specific field it is possible to create generic CustomEditor for all MonoBehaviours and ScriptableObjects (like how [ButtonMethodAttribute](https://github.com/Deadcows/MyBox/blob/master/Attributes/ButtonMethodAttribute.cs) works) and treat ConditionalField as regular C# attribute, with reflection. 
But in this case if I'll exclude some specific fields out of inspector drawer, I'll probably mess up other propertydrawers... 

Anyway, I need to test this out and don't have much time for that at the moment, but I want to solve this problem too :)

**Comment by sctiendat** [comment]
I encountered a similar problem and I found a temporary solution. I hope it helps someone.
With the example of nipunasudha:
`   
public struct AgeArray { public int[] ageArray; }
public bool showAges;
[ConditionalField(nameof(showAges))] public AgeArray ageArray;
`

**Comment by ModProg** [comment]
> I encountered a similar problem and I found a temporary solution. I hope it helps someone.
> With the example of nipunasudha:
> 
> ```
> [System.Serializable]
> 
> public struct AgeArray { public int[] ageArray; }
> 
> public bool showAges;
> 
> [ConditionalField(nameof(showAges))] public AgeArray ageArray;
> ```
This seams to work, but doesn't show the array itself.

**Comment by sctiendat** [comment]
> This seams to work, but doesn't show the array itself.
@ModProg  Do you add [System.Serializable] ? I tested and it worked correctly.
<img width="320" alt="Screenshot at May 16 05-12-19" src="https://user-images.githubusercontent.com/30305416/82100598-3adee080-9734-11ea-9ec1-09cd96633cab.png">
<img width="318" alt="Screenshot at May 16 05-12-35" src="https://user-images.githubusercontent.com/30305416/82100602-3f0afe00-9734-11ea-8818-ea6f5f2b07e6.png">

**Comment by Deadcows** [comment]
Got a nice idea! I might add some base type, like CollectionWrapper to use as a base class in AgeArray, and handle such fields to draw the array element directly, without this "⯆Age Array ⯆Age Array" duplication 🤓 
And that'll be the documented way to do collections with ConditionalField 👍🏻

@sctiendat thanks a lot for this solution. I used this approach many times, but not treated it as a solution for ConditionField for some reason😐

**Comment by Deadcows** [comment]
[Finally](https://github.com/Deadcows/MyBox/commit/d286769a353609da327f56fce2fece3680e00cc3), I fixed a long-lived bug with ConditionalAttribute, this allows us to do this:

```
	public bool ShowWrappedCollection;
	[ConditionalField(nameof(ShowWrappedCollection))]
	public GOCollection WrappedCollection;

	[Separator]
	public bool ShowReorderable;
	[ConditionalField(nameof(ShowReorderable))]
	public ReorderableGameObject ReorderableCollection;


	[Serializable]
	public class GOCollection : CollectionWrapper<GameObject> {}
```

![image](https://user-images.githubusercontent.com/969858/82177766-33116e80-98e3-11ea-9673-72378d6db221.png)

[CollectionWrapper](https://github.com/Deadcows/MyBox/commit/efbb41268ada96455d60a2bf1e8235059044a9e6) allows to draw wrapped collection directly

phew!

**Comment by sctiendat** [comment]
Thank you very much DeadCows. It is really neccessary for me.
