### ISSUE TITLE
Strange Foldout Behaviours

### ISSUE THREAD

**Issue by hikariakio** [Deadcows/MyBox#100]
` [Foldout("Example",true)]
    [SerializeField] float m_speed;
    [SerializeField] string _age;
    [SerializeField] bool m_isDead;

    //---------------------------------// I want to End FOLDOUT HERE
    [SerializeField] float m_otherThings;`

Before question , is there anything I can do to end the Foldout part before m_otherThings other than putting attribute on each variable? 

The issue is ,when using Foldout, variables names on the inspector became weird. Usually, without foldout, Unity can omit those perfixes and underscroll. Is there any work around?

Thank you!
 
![Report_Foldout](https://user-images.githubusercontent.com/31139816/89222111-73d37680-d5fa-11ea-88f9-5c83d3fb7073.PNG)

**Comment by ThatDylanDude** [comment]
By setting the second arg to true, the foldout will include all the variables below it. Instead, set to false (or don't set it at all - it defaults to false) and place the attribute above each variable you want included in the foldout (make sure the string names are the same).

**Comment by Deadcows** [comment]
Yep, it's possible! 
You able to specify what field should be placed in which foldout by placing Foldout attribute per field.
And to fix naming issue you may use OverrideLable attribute, like this: 

[Foldout("Setup"), OverrideLabel("Transform")] public Transform selfTransform;
[Foldout("Data"), OverrideLabel("HP"), SerializeField] private int _hp;
[Foldout("Data"), SerializeField] private int _ap;
public float MoveSpeed = 4;

![image](https://user-images.githubusercontent.com/969858/129885372-4c6bcedd-f8f0-41aa-8e3b-87e53b5875d0.png)
