### ISSUE TITLE
Conditional Field Attribute

### ISSUE THREAD

**Issue by UpperpikUgur** [Deadcows/MyBox#101]
Conditional Field Attribute does not work for array

**Comment by wolfi2** [comment]
Same!
But I also get the warning: "Property MyProperty in object MyObject caused: Array fields is not supported by [ConditionalFieldAttribute]". So it seems "normal".

**Comment by Deadcows** [comment]
Yep, unfortunately there is nothing I can do to handle native array with ConditionalField, but [there is a workaround](https://github.com/Deadcows/MyBox/wiki/Attributes#conditionalfield-with-arrays) 🤓
