### ISSUE TITLE
ConditionalField and inherited class variables

### ISSUE THREAD

**Issue by LoneDev6** [Deadcows/MyBox#102]
Is there a way to hide inherited class variables from child class using ConditionalField?
I want to show inherited class variables only if a specific enum attribute is set to a value.

Thanks

**Comment by Deadcows** [comment]
It is completely doable, yet two years passed and it is probably long time necro 😣 _(sorry)_
Although Conditional must be set on the field (of the base class) itself and it is a horror from object-oriented point of view.
But it's works. And if you use BaseClass directly or any other child class without "HideTestA" field it will be simply discarded (and TestA field will be displayer as it should)

	[Serializable]
	public class ChildClass : BaseClass
	{
		public bool HideTestA;
	}
	
	[Serializable]
	public class BaseClass
	{
		[ConditionalField("HideTestA", true)]
		public string TestA;
		public string TestB;
	}
