### ISSUE TITLE
ToCamelCase in MyString.cs is not working

### ISSUE THREAD

**Issue by oscar-hotdot** [Deadcows/MyBox#103]
![擷取](https://user-images.githubusercontent.com/47516552/91828986-69e17980-ec73-11ea-8c64-2052bb13c040.PNG)
![擷取1](https://user-images.githubusercontent.com/47516552/91828996-6d750080-ec73-11ea-9e64-36bc42e3c5ba.PNG)
I tried to fix it but I don't know the regex pattern.....
I need the help. Thank you very much

**Comment by Deadcows** [comment]
Thanks to @derfium this issue is fixed!
