### ISSUE TITLE
ConditionalField not showing lists properly

### ISSUE THREAD

**Issue by android272** [Deadcows/MyBox#104]
I have a ConditionalField that hides a List\<item\> called keys. As you can see from the screenshot below I have 100 items in the list but the checkbox above the list is not checked. So the List header Should not be shown. If I check the box I do not see the contents of the list. So it is half working.

![image](https://user-images.githubusercontent.com/5912527/93296273-e2d8e900-f7bc-11ea-99b4-041b2b32467b.png)

**Comment by Deadcows** [comment]
I bet that was fixed some time ago. Finally! 😑
