### ISSUE TITLE
BUG: [AutoProperty] doesn't set values in prefab mode and throws errors

### ISSUE THREAD

**Issue by Tymski** [Deadcows/MyBox#109]
In the following example, there is no way to set the rect transform reference
![image](https://user-images.githubusercontent.com/8183632/100362591-ec23d480-2ffb-11eb-84a5-e9bee8affdb3.png)
Because the script doesn't work in prefab mode.

**Comment by Tymski** [comment]
![image](https://user-images.githubusercontent.com/8183632/100364002-cf889c00-2ffd-11eb-8dae-9bdfae77519c.png)

**Comment by Deadcows** [comment]
AutoProperty should fill itself when asset is saved in Prefab Mode. It's surely better to fill it up on Open and Dirty events, I'll fix that! But this errors.. I'll check it, thanks!

**Comment by Deadcows** [comment]
oh, btw, Tymski, thanks a lot for bunch of reports! Most of the stuff I made for myself and never thought it will be used by someone 😁

**Comment by Deadcows** [comment]
AptoPropertyAttribute [should work much better](https://github.com/Deadcows/MyBox/commit/23fab219f4d1dd2eb4e6106c66aca27442977ab6) now, with properties check on "prefab mode open" event
