### ISSUE TITLE
[Separator()] attribute look's a bit ugly

### ISSUE THREAD

**Issue by 7azmi** [Deadcows/MyBox#110]
this is not an issue but could be better with a little **spacing**
![Screenshot_200](https://user-images.githubusercontent.com/58638184/100651269-469f9680-3356-11eb-93a4-ac0b57b8b23d.png)

**Thanks!**

**Comment by Tymski** [comment]
It's not a bit ugly it looks disgusting :D

**Comment by TehMightyPotato** [comment]
Set `withOffset=true` like `[Separator("Title",true)]`. Doesn't look half-bad with offset enabled.

**Comment by Deadcows** [comment]
Oh my 😀 yeah, quite embarrassing! I made it to take a bit more space and also separator without title now more centered. 
Yeah, now it'll be nice to find some colour that looks good in both dark and light themes 😁 [Latest commit with the changes.](https://github.com/Deadcows/MyBox/commit/931a849b50137f0f620453e795b320f3be101a2c)

my before and after
![2021-03-17_13-50-34](https://user-images.githubusercontent.com/969858/111457366-250dc380-8729-11eb-9458-9f8d2d0679b2.png)
![2021-03-17_13-51-14](https://user-images.githubusercontent.com/969858/111457372-26d78700-8729-11eb-9fc8-1cca79cec3c2.png)
