### ISSUE TITLE
Duplicating Error

### ISSUE THREAD

**Issue by 7azmi** [Deadcows/MyBox#112]
Some fields are sub that should show inside specific enum conditions so we need more than one Con-Field
Could you please solve the Duplicating Error?
or override a "true bool" like Foldout attribute

Example:
```
    [ConditionalField(nameof(exitTo), false, ExitTO.Door)]
    [SerializeField] Door target;

    [ConditionalField(nameof(exitTo), false, ExitTO.Door)]
    [ConditionalField(nameof(target))] //Duplicating issue 
    [SerializeField] string doorName;
```

This Error is a Struggle in my project
will be appreciated for fixing it

Thank you!

**note**
I tried to donate but couldn't 'The recipient has exceeded the receiving limit'

**Comment by Deadcows** [comment]
Sorry for late response (oh my god two years 😫) 

Multiple conditions is now supported! Yet there is should be only one attribute, you may compose it like this

		public bool A;
		public bool B;
		public enum Test {C, D, E}
		public Test T;
		[ConditionalField(nameof(A))] 
		public string IsA;
		[ConditionalField(nameof(B), true)] 
		public string NotB;
		[ConditionalField(nameof(A), nameof(B))] // Simply put multiple field names
		public string AandB;
		// To invert some of fields you need to pass two arrays, where prop[0] compared with inverse[0] (if any)
		[ConditionalField(new[] { nameof(A), nameof(B) }, new[] { true })] 
		public string NotAandB;
		[ConditionalField(new[] { nameof(A), nameof(B) }, new[] { false, true })]
		public string AnotB;
		[ConditionalField(new[] { nameof(A), nameof(B) }, new[] { true, true })]
		public string NotAandNotB;
		[ConditionalField(new[] { nameof(T), nameof(A), nameof(B) }, new[] { false, true, true }, Test.C )]
		public string NotAandNotBButC;

and in your case 

		[ConditionalField(new[] {nameof(exitTo), nameof(target)}, null, ExitTO.Door)]
		[SerializeField] string doorName;

It's a bit cumbersome at the first glance and lacking documentation at the moment, but (finally) works!


_haha now I know why no one donated for the last two years_ 😂

**Comment by 7azmi** [comment]
Hello there, I’m still alive by the way and currently using Odin but thank
you for the fix!

I’m also shocked that it has been two years. I still remember my request as
if it was last week.

Glad to see your reply man!
