### ISSUE TITLE
1.5.1 Release message but no way to update through Packager Manager

### ISSUE THREAD

**Issue by Garfounkel** [Deadcows/MyBox#117]
Every time I open Unity I get a console message about updating MyBox:
> It's time to update MyBox :)! Use "Tools/MyBox/Update MyBox". Installed version: 1.5.0. Latest version: 1.5.1

Unfortunately there's no "Update MyBox" option under "Tools/MyBox/Update MyBox".
![image](https://user-images.githubusercontent.com/10576004/103418198-f3577880-4b8d-11eb-8ea5-a8a9baa8c90e.png)

Here's what "MyBox Window" shows:
![image](https://user-images.githubusercontent.com/10576004/103418341-80023680-4b8e-11eb-9140-a8ee30fc1865.png)

In the package manager no Update button either:
![image](https://user-images.githubusercontent.com/10576004/103418391-b93aa680-4b8e-11eb-9cf9-18ebb33db9ed.png)

My manifest.json looks like this:
```
{
  "scopedRegistries": [
    {
      "name": "NPM Registry",
      "url": "https://registry.npmjs.org",
      "scopes": [
        "com.mambojambostudios.unity-atoms-core",
        [... more atoms scopes]
      ]
    }
  ],
  "dependencies": {
    [...],
    "com.mybox": "https://github.com/Deadcows/MyBox.git",
    [...]
  }
}
```
As you can see, no mention of "lock" in my manifest.

ps: Thank you @Deadcows for releasing and maintaining MyBox for free, it's been an incredible help you have no idea.

**Comment by doodoori2** [comment]
It's because the package name has been changed to "com.domybest.mybox" from "com.mybox".
please check this link https://github.com/Deadcows/MyBox/issues/117

**Comment by Garfounkel** [comment]
Oh I see, that make sense my bad. Thanks!

**Comment by doodoori2** [comment]
It was the same problem that I came to this repo. :)
