### ISSUE TITLE
[Bug] AnimationStateReference state duplication within List

### ISSUE THREAD

**Issue by Garfounkel** [Deadcows/MyBox#118]
All AnimationStateReference within a list seem to be referring to the same instance. Changing one changes all other.

![bug_mybox](https://user-images.githubusercontent.com/10576004/103463615-f1c4b680-4d2d-11eb-9c53-b9f0ac9e1714.gif)

### Reproducing
```csharp
using System.Collections.Generic;
using MyBox;
using UnityEngine;

public class BulletinAnimatorListener : MonoBehaviour
{
  public List<AnimationStateReference> animationList;
}
```

**Comment by Garfounkel** [comment]
Also, note that the animator field is not automatically set for AnimationStateReference within a list and the "reset" button doesn't work either.

**Comment by Deadcows** [comment]
[Fixed!](https://github.com/Deadcows/MyBox/commit/7a196f9843eebf9db450968c9402cdcb19a29994) Thanks for the report! 🤓
