### ISSUE TITLE
Reorderable Lists with DisplayInspector not working

### ISSUE THREAD

**Issue by VirsabiMunk** [Deadcows/MyBox#119]
Title - may be unnecessary to fix with unity 2020.2 reorderable collection though. :)

**Comment by GeorgeManeta** [comment]
Yep, broken in Unity 2020.2.6f1, currently using the [NonReorderable] attribute to make only the old array drawer show.
![image](https://user-images.githubusercontent.com/29165387/110121405-19bbaf00-7d9d-11eb-9189-0a0532b28c9f.png)

Also, the values in the reorderable drawer seems to don't update on inspector changes, maybe a ApplyModifiedProperties missing?

**Comment by CorneliusCornbread** [comment]
![image](https://user-images.githubusercontent.com/8294697/112344416-0f048380-8c92-11eb-9d2b-d1443e5de22b.png)
Having a similar issue on 2020.3.1f1 LTS

**Comment by Deadcows** [comment]
Oh my, that's embarrassing how long this issue is hanging here!
[I made some changes](https://github.com/Deadcows/MyBox/commit/559fa1f866408cc3de9653e48f9799904e07aaf9) to make it work with new collections.
Please check it out and let me know if I broke something else in the process 😁
