### ISSUE TITLE
GUIStyle names incorrect in SearchableEnumAttribute.cs

### ISSUE THREAD

**Issue by hnguyen094** [Deadcows/MyBox#120]
In `MyBox/Attributes/SearchableEnumAttribute.cs`, [lines 307-309](https://github.com/Deadcows/MyBox/blob/900922be56cf6d547df65650037da21ef3ba54d1/Attributes/SearchableEnumAttribute.cs#L307-L309):
```
		private static readonly GUIStyle SearchBox = "ToolbarSearchTextField";
		private static readonly GUIStyle CancelButton = "ToolbarSearchCancelButton";
		private static readonly GUIStyle DisabledCancelButton = "ToolbarSearchCancelButtonEmpty";
```
But due to a typo in Unity (I specifically am on 2020.2.1f1), it should be (without the 'r' in 'Search'):
```
		private static readonly GUIStyle SearchBox = "ToolbarSeachTextField";
		private static readonly GUIStyle CancelButton = "ToolbarSeachCancelButton";
		private static readonly GUIStyle DisabledCancelButton = "ToolbarSeachCancelButtonEmpty";
```

You can see Unity's typos here:
https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/GUI/EditorStyles.cs#L449
https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/GUI/EditorStyles.cs#L451
https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/GUI/EditorStyles.cs#L452

Unclear when this change happened but it seems to go all the way back to Unity version 2017.1.0a3.

**Comment by Deadcows** [comment]
Thanks! It is fixed, finally 🤗

I'm back on track with MyBox, promise 🤔
