### ISSUE TITLE
[AssetReference] ConditionalField Serialization

### ISSUE THREAD

**Issue by suiboli314** [Deadcows/MyBox#121]
### Enviroment: 
Editor 2020.2, Addressables 1.16.16, built-in UI Elemen

### Behavior
`AssetReference` field with `[ConditionalField]` Attribute Tag will cause non-fatal bug, see image. 
![20210203152227](https://user-images.githubusercontent.com/23085379/106712845-81fb6180-6634-11eb-9f91-e4e6888819b6.jpg)

**Comment by Tymski** [comment]
It's not just this, as most of the attributes in MyBox don't work when you use multiple attributes

**Comment by Deadcows** [comment]
I [made some changes](https://github.com/Deadcows/MyBox/commit/49c3be932c305a97e639d859454f32c49c4248f5) to ConditionalField, hopefully it will resolve this issue
