### ISSUE TITLE
NextIndexInCircle Only works for increments of 1

### ISSUE THREAD

**Issue by idbrii** [Deadcows/MyBox#127]
https://github.com/Deadcows/MyBox/blob/1c9857f6651fe55fad155bc38025cbea3fea196f/Extensions/MyCollections.cs#L167,L170

If the input is more than 1 away from a valid index, the result is wrong across end boundaries.

If you use this to iterate through an array with a stride of 5, when you loop the array you start at the beginning instead of 5 away from your last choice. Essentially, should use modulo: https://stackoverflow.com/questions/1082917/mod-of-negative-number-is-melting-my-brain

Also, array.length == 0 is checked twice (already checked in nullorempty) and returns an invalid index 0 for an empty array. Maybe it's supposed to check length == 1?

**Comment by Deadcows** [comment]
Nice! Never assumed such usage 😁 suggested changes are in the [latest commit](https://github.com/Deadcows/MyBox/commit/26e7861f5804f8b0b864b441d06e2491c966f569)
