### ISSUE TITLE
Unity closes when package is installed

### ISSUE THREAD

**Issue by misterblokhead** [Deadcows/MyBox#128]
When I have the package installed, Unity either doesn't open, or crashes after a couple of seconds. This depends on the way it is installed.
If I install it by dropping the package in my assets, Unity doesn't open.
When I Install it by putting it in my manifest, it opens but crashes/closes after a few seconds.

**Comment by Deadcows** [comment]
Oh my 😨 Can you please attack editor log right after the crash? Should be here: 
C:\Users\username\AppData\Local\Unity\Editor\Editor.log

**Comment by misterblokhead** [comment]
Thanks for the quick response.
I've made a couple of logfiles:
This logfile is using GIT on the bottom of the manifest
[Editor.log](https://github.com/Deadcows/MyBox/files/6159387/Editor.log)
This logfile is using GIT on the top of the manifest
[Editor.log](https://github.com/Deadcows/MyBox/files/6159393/Editor.log)
This logfile is by dropping the entire package into my assets when unity was already running
[Editor.log](https://github.com/Deadcows/MyBox/files/6159406/Editor.log)

As far as I can tell, all of the logfiles end on: wakeup_pipes_init: connect () failed, error (0).

Thanks in advance!

**Comment by Deadcows** [comment]
That's strange, I see no mentions of editor crash 🙄.
Maybe I missing something... I'll write on Unity forums about it, hopefully someone will have some ideas about it

**Comment by Deadcows** [comment]
Please check out latest version and [install it via UPM](https://github.com/Deadcows/MyBox/wiki/Installation)
Note if issue remains
