### ISSUE TITLE
Creating a prefab in an empty directory

### ISSUE THREAD

**Issue by nipunasudha** [Deadcows/MyBox#13]
A prefab cannot be created in a newly created empty directory. When I drag the gameobject into the directory, the directory is already gone, cleaned up by the empty dir remover.
Unity gives me an error saying dir not found.

I use Unity 2018.3.7f1

**Comment by Deadcows** [comment]
Apparently new Prefab system forces Save Assets event on prefab creation. Well, it makes sense :)
I made a fix for this [in this commit](https://github.com/Deadcows/MyBox/commit/e20bb0bc299bda76ce5fc7b7008e7b964a184a68)
Thanks for the report
