### ISSUE TITLE
DefinedValues does not work

### ISSUE THREAD

**Issue by 7azmi** [Deadcows/MyBox#130]
DefinedValues simply returns 0.
 
```
    [DefinedValues(.75f, 0.8125f)]
    public float handFit;
    [ButtonMethod]
    void PickupFlag()
    {
        //flag.theFlag.transform.parent = transform;
        //flag.theFlag.transform.localPosition =  new Vector3(handFit, 0, 0);
        Debug.Log(handFit); // 0
    }
```

**Comment by Deadcows** [comment]
but popup in the inspector shows the correct values? Or with some errors? Is this type (with handFit) is stored in collection on the MB or maybe it's displayed via DisplayInspector attribute?

**Comment by Deadcows** [comment]
Anyway, just [commited updated version](https://github.com/Deadcows/MyBox/commit/4dfdb5a5ee47574982e40e9c311300bdb103a2db) of the attribute. Not sure if it'll help you, but I fixed some edge-case scenarios. Please check it out and reopen the issue if problem remains
