### ISSUE TITLE
Not able to import the asset

### ISSUE THREAD

**Issue by UnimaginaryUnit** [Deadcows/MyBox#131]
Hello! I've imported the project with UPM and got the following errors:

```
Assets\ExternalAssets\MyBox-master\Tools\Internal\MyBoxSettings.cs(10,6): error CS0122: 'FilePathAttribute' is inaccessible due to its protection level
Assets\ExternalAssets\MyBox-master\Tools\Internal\MyBoxSettings.cs(10,55): error CS0122: 'FilePathAttribute' is inaccessible due to its protection level
```

I'm using Unity 2019.3.10f1, and as far as I understand, ScriptableSingleton is a Unity 2020.x.x-only feature. Would be really nice to have Unity version requirements on the repo page, or a 2019.x.x-compatible version of the project, without ScriptableSingleton functionality.

Thanks for your amazing tool anyways ✨

**Comment by Deadcows** [comment]
oh dang, my bad! I didn't noticed that ScriptableSingleton is that new (but I thought "how did I missed that!?" when I saw it 😁). I reversed changes that brings ScriptableSingleton into the project. Please try to import again
