### ISSUE TITLE
Forcing update through package manager

### ISSUE THREAD

**Issue by Garfounkel** [Deadcows/MyBox#132]
Was struggling to update to 1.6.0 despite having removed "lock" from my manifest.json and having the correct package name. However, I found a way to force the package manager to update and I thought @Deadcows might want to include this in the Readme. So in order to force the update, open the package manager, click the plus icon, then "Add package from git url...", then paste: https://github.com/Deadcows/MyBox.git and click "Add". This should force the package manager to update MyBox, at least it did for me.
![image](https://user-images.githubusercontent.com/10576004/113727054-121d5c00-96f5-11eb-9ddc-76fa8c05fa45.png)
![image](https://user-images.githubusercontent.com/10576004/113727404-645e7d00-96f5-11eb-9fb7-cf28280d2168.png)

**Comment by Deadcows** [comment]
Thanks a lot for mentioning that! I fixed that in 1.6.1, it should work fine with "Update" button. But I'll update Installation section in docs, it's outdated for sure
