### ISSUE TITLE
"Unable to read MyBoxSettings, set to defaults"

### ISSUE THREAD

**Issue by KingTempest07** [Deadcows/MyBox#136]
Maybe I'm just dumb and can't find the "set to defaults button," but this just appeared while (or possibly before) I was trying to build a .sln file and I can't find anything on it online. I also can't edit the files since this is the auto-updating version.

```
Unable to read MyBoxSettings, set to defaultsSystem.InvalidCastException: Specified cast is not valid.
  at MyBox.Internal.MyBoxSettings.LoadSettings () [0x00000] in 

C:\Users\jmhus\Documents\Escape\Library\PackageCache\com.domybest.mybox@1.6.2\Tools\Internal\MyBoxSettings.cs:111 
UnityEngine.Debug:LogError (object)
MyBox.Internal.MyBoxSettings:LoadSettings () (at Library/PackageCache/com.domybest.mybox@1.6.2/Tools/Internal/MyBoxSettings.cs:115)
MyBox.Internal.MyBoxSettings:LoadOrCreate () (at Library/PackageCache/com.domybest.mybox@1.6.2/Tools/Internal/MyBoxSettings.cs:93)
MyBox.Internal.MyBoxSettings:get_Instance () (at Library/PackageCache/com.domybest.mybox@1.6.2/Tools/Internal/MyBoxSettings.cs:68)
MyBox.Internal.MyBoxSettings:get_AutoSaveEnabled () (at Library/PackageCache/com.domybest.mybox@1.6.2/Tools/Internal/MyBoxSettings.cs:19)
MyBox.Internal.MyBoxFeatures:get_AutoSaveIsEnabled () (at Library/PackageCache/com.domybest.mybox@1.6.2/Tools/Internal/MyBoxFeatures.cs:27)
MyBox.Internal.MyBoxFeatures:.cctor () (at Library/PackageCache/com.domybest.mybox@1.6.2/Tools/Internal/MyBoxFeatures.cs:16)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes (System.Type[])
```

**Comment by Deadcows** [comment]
It was set to defaults automatically, so you don't have to bother. 
This is caused by issue [I fixed last](https://github.com/Deadcows/MyBox/commit/b90e45e07591f465004f33f53bdb62ffabab6efe) week and part of "unreleased" fix. To grab MyBox with all changes you need to manually update, even if there were no warnings about new version — go to Tools/MyBox/MyBox Window and click Update button

Hope this helps 🙂

**Comment by KingTempest07** [comment]
This removed that bug, but instead, another popped up:

`'MyBox.Internal.MyBoxSettings' is missing the class attribute 'ExtensionOfNativeClass'!`

Followed by several of these:

`Fixing reference to the runtime script in scene file!`

**Comment by Deadcows** [comment]
I checked it out. Thankfully it's just a one-time warning, you won't be seeing it again 🤗

**Comment by KingTempest07** [comment]
Okay, probably should have tried restarting it lol. It's fixed... for now...
