### ISSUE TITLE
not really an issue but I have no idea how to talk to you otherwise

### ISSUE THREAD

**Issue by kobi666** [Deadcows/MyBox#137]
I wanted an example on how to use the weighted random,
Couldn't figure out myself :\

**Comment by Deadcows** [comment]
Good point, I've needed to add docs for extensions a long time ago!
Here is [a bit of info about weighted randoms](https://github.com/Deadcows/MyBox/pull/133), specifically this test case:
```
var weights = new[] { 6, 3, 1 }; // insert your own weights
var rolls = new List<int>();
for (int i = 0; i < 10_000; ++i)
	rolls.Add(weights.GetWeightedRandom(w => w));
rolls.GroupBy(r => r).ForEach(g => Debug.Log($"weight: {g.Key}, number of rolls: {g.ToArray().Length}"));
```

or this made up example, where out of all items you will select regular item with 70% chance and epic with 10% chance

```
items.GetWeightedRandom(item => {
    if (item.Grade == ItemGrade.Epic) return 1;
    if (item.Grade == ItemGrade.Rare) return 3;
    if (item.Grade == ItemGrade.Regular) return 7;
}));
```

Hope it makes sense, I didn't have a chance to use it by myself yet 😁
