### ISSUE TITLE
BUG: MustBeAssigned not working in Unity 2019.4 LTS

### ISSUE THREAD

**Issue by angelsalascalvo** [Deadcows/MyBox#138]
Tried to use MustBeAssigned in a script reference in unity 2019.4 but it doesn't seem to be working properly. No error is received when the variable does not have the reference assigned.

![image](https://user-images.githubusercontent.com/34268023/115223861-8ea83580-a10c-11eb-93e8-356733811a13.png)
![image](https://user-images.githubusercontent.com/34268023/115223690-602a5a80-a10c-11eb-9556-8135e80f2b49.png)
![image](https://user-images.githubusercontent.com/34268023/115223782-76d0b180-a10c-11eb-8980-5d0e7ea160c8.png)

**Comment by rfadeev** [comment]
Hi,

Just tested the attribute with Unity 2019.4.18f1 and got the errors when the field was not assigned. I used following test class:
```csharp
using UnityEngine;
using UnityEngine.Playables;

public class MustBeAssignedTest : MonoBehaviour
{
    [MyBox.MustBeAssigned]
    public PlayableAsset myTestField;
}
```

Error is triggered on saving assets8/saving prefab in prefab mode. Did you try doing any of those saves? To save assets you can do "File -> Save Project".

Hope that helps!

**Comment by angelsalascalvo** [comment]
@rfadeev You are right, the error is thrown when saving the project. Thought it would run in OnValidate()...
Maybe it could be a future improvement. 

Thanks!
