### ISSUE TITLE
[Feature request] SeparatorAttribute "after field" parameter

### ISSUE THREAD

**Issue by Silentor** [Deadcows/MyBox#141]
Hello!
Sometimes I want to separate base class inspector from derived class inspectors. I can use a Space or Separator attributes on first field of all child classes, but it should be useful to place separator *after* last field of base class. 
Yes, we cannot place attribute on empty space :) But we can implement a parameter of SeparatorAttribute to draw separator after tagged field. So one separator in base class works with all derived classes inspectors.

**Comment by Deadcows** [comment]
Unfortunately it's not that simple 🤔 DecoratorDrawer only allows to occupy space on top of the field.
As a workaround it's possible to create some sort of Separator type, but I don't like that idea of cluttering the code with junky fields. I put this idea to my todo, maybe I'll have better ideas later
