### ISSUE TITLE
Count/length on collectionWrappers?

### ISSUE THREAD

**Issue by DonTomasDeLaVega** [Deadcows/MyBox#149]
Pretty much sum'd it up, is there a way to get the length of a collectionWrapper?

**Comment by Deadcows** [comment]
Collection wrapper is just a class with the only array field in it, so you may manipulate with this "Value" field as you would with regular array 😬

`_wrapperCollection.Value.Length`

**Comment by DonTomasDeLaVega** [comment]
Oh, okay, nice! And for indexing? Can i do `_wrappedCollection.Value.[i]` ?

**Comment by Deadcows** [comment]
Sure! But without dot before parenthesis:

.Value[i]

**Comment by DonTomasDeLaVega** [comment]
Heyyy! Nice! And one last question: since it's the array class, we can't have the "Add" method from lists, right? Or can we add it by hand in its class?

**Comment by Deadcows** [comment]
Your code should work perfectly 🙂
Slightly more performant approach is to use Array.Resize function:

```
var array = new[] {1, 2, 3};
Array.Resize(ref array, array.Length + 1);
array[array.Length - 1] = 4;
```

this way you don't need to create new array and copy all previous values

**Comment by DonTomasDeLaVega** [comment]
![image](https://user-images.githubusercontent.com/47381187/120606626-ab47c500-c44f-11eb-8521-852fc0b17c76.png)
As so? :)
Thanks so much for your reactivity!

**Comment by Deadcows** [comment]
Yep 😁

**Comment by DonTomasDeLaVega** [comment]
Thanks! :)
