### ISSUE TITLE
Visual Studio not recognising the package?

### ISSUE THREAD

**Issue by DonTomasDeLaVega** [Deadcows/MyBox#152]
Worked fine yesterday, but now it doesn't recognises the namespaces... Any ideas?
Updated the package: nothing
Here's what visual studio sees
![image](https://user-images.githubusercontent.com/47381187/120763695-c3831700-c517-11eb-9d6e-3475f24ba337.png)
![image](https://user-images.githubusercontent.com/47381187/120763725-cc73e880-c517-11eb-8025-e8342ba35e8a.png)
("The element 'attributeBase.cs' is not findable inside the folder of the project. It may have been renamed, deleted or moved.")

**Comment by DonTomasDeLaVega** [comment]
![image](https://user-images.githubusercontent.com/47381187/120764984-05f92380-c519-11eb-9cd7-bb8ac1d69c3c.png)
Well, simply click this :)

**Comment by Deadcows** [comment]
Yep, currently it is considered a bug in Unity, but it is a viable workaround for now 🤔
