### ISSUE TITLE
Documentation: Add a use case for AutoProperty as type's list of references

### ISSUE THREAD

**Issue by tonygiang** [Deadcows/MyBox#155]
So while experimenting with the new and expanded `AutoProperty`, I came across a use case that came out as a completely natural result of combining certain things together.

Apply a `AutoProperty` attribute with Scene/Asset/Any mode to a collection field, then save the project. This creates a list of references to all instances/prefabs/ScriptableObjects that use the element type of the collection field that _automatically updates itself_ everytime you save your changes to the scene/project.

Example: `[AutoProperty(AutoPropertyMode.Scene)] public Camera[] AllCameras;` will keep references to all cameras in a scene

The GameObject that contains these references can then be tagged with `EditorOnly` so that you get a convenient list of references to keep track of with no runtime impact.

This is too cool of a use case to not instruct developers to use.

**Comment by Deadcows** [comment]
Good idea! Added this to docs

![image](https://user-images.githubusercontent.com/969858/121158704-3d3a3e00-c853-11eb-94aa-25983fc7d945.png)
