### ISSUE TITLE
Changelog: Remove references to SelectWithIndex and SelectManyWithIndex

### ISSUE THREAD

**Issue by tonygiang** [Deadcows/MyBox#159]
Seeing the 1.6.2-1.7.0 changelog containing both
```Extensions: MyCollections.SelectWithIndex and SelectManyWithIndex - like LINQ.Select, but with index passed along the item into selector```
and
```Breaking Changes: MyCollections.SelectWithIndex and SelectManyWithIndex removed (Linq.Select and SelectMany functionality duplication)```
is kind of weird.

**Comment by Deadcows** [comment]
oh, haha, right 😁 long time passed since I released new version of MyBox, and this "breaking changes" was about unreleased feature. So, I may simply remove both lines! 😎
