### ISSUE TITLE
Add package.json so can use with Unity Package Manager

### ISSUE THREAD

**Issue by StewMcc** [Deadcows/MyBox#16]
Cool toolbox, any chance of adding package.json so can be used with Unity's Package Manager?
Shows what Unity latest version is and any dependencies it has as well.

```
{
  "name": "com.mybox",
  "displayName": "MyBox",
  "version": "0.0.1",
  "unity": "2018.3",
  "description": "DeadCows My Box",
  "dependencies": {
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0"
  }
}
````

mob-sakai upm extension:
https://github.com/mob-sakai/UpmGitExtension/tree/upm
and his tutorial for the custom branch for upm, may be easier for maintaining:
https://www.patreon.com/posts/25070968

**Comment by Deadcows** [comment]
Interesting idea! I'll check this out, thanks

**Comment by KorDum** [comment]
Please add like these https://github.com/h8man/NavMeshPlus/issues/12

**Comment by Deadcows** [comment]
Sorry for this delay guys. I dug into this and seems like package.json is fine but when I change version I see no upsates in Package Manager and no version history 😨 I made it without extra brunch however...

Dependency should look like this: 
"com.mybox": "https://github.com/Deadcows/MyBox.git#master"
But as far as you wont see any new versions I not recommend to use it yet

**Comment by KorDum** [comment]
It works fine! Thanks!

**Comment by Deadcows** [comment]
Now with the latest version of MyBox you'll receive message if there is update available! 
And you're able to update UPM version with "Tools/MyBox/Update window"

So please download latest version :)
