### ISSUE TITLE
Request: ButtonMethod with ConditionnalField

### ISSUE THREAD

**Issue by DonTomasDeLaVega** [Deadcows/MyBox#163]
Hi! I'm currently creating some kind of custom inspector for one of my script, and your package is really helpful!
But i wondered if there was a way so that button methods were compatible with Conditional fields **
![image](https://user-images.githubusercontent.com/47381187/123920904-c2160480-d986-11eb-8b31-57a433e36299.png)
**
it would really be cool, wouldn't it?
I wondered if you ever thought of this kind of use that goes really far with the conditionnal field attribute lol
(Would be neat to hide separators too though 👀)

**Comment by Deadcows** [comment]
Nice idea! Not too hard to implement, I think 🙄 I'll look into it when im out of crunch mode on my work 😁

**Comment by Deadcows** [comment]
It is [finally possible](https://github.com/Deadcows/MyBox/blob/master/CHANGELOG.md#:~:text=%5BMustBeAssigned%5D%20public%20Transform,ChildTransform%20%3D%20choldGO.transform%3B%0A%7D)! Also, along with this addition, Conditional attributes now allows [to use method as condition](https://github.com/Deadcows/MyBox/blob/master/CHANGELOG.md#:~:text=public%20int%20Value,public%20bool%20JobTaskIsDone%3B) and also [to check several fields](https://github.com/Deadcows/MyBox/blob/master/CHANGELOG.md#:~:text=public%20enum%20Test,public%20string%20NotAandNotBButC)!
