### ISSUE TITLE
Request: Integrate SceneAttribute with BuildScenes

### ISSUE THREAD

**Issue by Medallyon** [Deadcows/MyBox#166]
Maybe this can be an optional attribute property, but I would like to limit the Scene selection in the inspector to scenes that are also part of my Build Settings, seeing as you can't load scenes not added to Build Settings anyway. NaughtyAttributes does this nicely, but I can't use it because of compatibility issues between that and MyBox.

**Comment by Deadcows** [comment]
[Done!](https://github.com/Deadcows/MyBox/commit/91442b80a398b1cc9dbfda18bba3bdc0387e4f8b) 

![image](https://user-images.githubusercontent.com/969858/130201055-1a9e0347-8947-4f52-8718-0a0fe5182fa1.png)
![image](https://user-images.githubusercontent.com/969858/130201112-50f7e155-e33d-4d94-baec-27d8a3fb4b1d.png)
