### ISSUE TITLE
Request: ConditionalField checks for enum type as an overload

### ISSUE THREAD

**Issue by KingTempest07** [Deadcows/MyBox#167]
I have a few enums in my script that change how the gun fires (e.g. firing type for burst, semi, or full auto firing), and there are some different values for the burst, one being shots per burst. Because of this, I tried using a conditional field to hide it when burst was deselected, but it checks for bools and my object for the enum it can't be used outside of functions to do something like "firingType == FiringType.burst." I would highly appreciate not having to make a custom inspector for each script with an enum in it

**Comment by DonTomasDeLaVega** [comment]
You... Can do this? 👀 
![image](https://user-images.githubusercontent.com/47381187/124440149-9b870d80-dd7a-11eb-950b-d18523176f34.png)
So for you it would be `[ConditionalField(nameof(firingType),false,FiringType.burst)]`

**Comment by KingTempest07** [comment]
sorry, I didn't realize there even was a wiki lol thanks for the help
