### ISSUE TITLE
Issue: Missing the class attribute

### ISSUE THREAD

**Issue by mjakub12** [Deadcows/MyBox#168]
Hi I just updated MyBox to latest 1.7.0 and after an update I am getting an error:

`'MyBox.Internal.MyBoxSettings' is missing the class attribute 'ExtensionOfNativeClass'!`

I tried to remove MyBox completely and do a fresh install but the error is still there.
Any idea how to fix it?
Thanks in advance :)

**Comment by Deadcows** [comment]
Yep, it's one-time error, shouldn't cause any issues
