### ISSUE TITLE
Issue with DisplayInspector and collections in 2020.3.12f1

### ISSUE THREAD

**Issue by TheWalruzz** [Deadcows/MyBox#169]
Recently, I tried using DisplayInspector to show contents of my ScriptableObject with character model, however it seems like changes made to list serialization in 2020.2 (enumerables are now reorderable by default, yay!) broke the collection serialization for this attribute

![Zrzut ekranu 2021-07-11 215521](https://user-images.githubusercontent.com/1745329/125208525-4e7fcb80-e293-11eb-8515-f98ba975d4fc.png)

One additional thing: seems like the label of the serialized field with DisplayInspector is empty as well.

Also, I've noticed a similar issue with #151, but my issue is connected to collections inside objects with DisplayInspectorAttribute :)

**Comment by Deadcows** [comment]
@TheWalruzz is there some place where I can read about your game? I've got to see dat Organic Hit Particles in action 🤓

**Comment by TheWalruzz** [comment]
@Deadcows I created a gamedev blog a while ago, but it hasn't been updated since May last year 😢 And since then I scrapped that project and started this new one, I really need to write something new there 😁
