### ISSUE TITLE
Possibility of 'MinMaxRange and RangedInt' inspector

### ISSUE THREAD

**Issue by nipunasudha** [Deadcows/MyBox#17]
RangedFloat inspector is a really useful editor utility. Same way, can we have a RangedInt inspector? Is it possible to implement the range slider for a discrete value range?

**Comment by Deadcows** [comment]
Sure! Nice idea. I [implemented ](https://github.com/Deadcows/MyBox/commit/7090dae216f1d980768e96b996db17065593ddfd) RangedInt type and MinMaxRangeAttribute works fine with it
