### ISSUE TITLE
Atributes composition

### ISSUE THREAD

**Issue by kfird214** [Deadcows/MyBox#180]
Add support for combining attributes together

for example `OverrideLabel` is not working with `CharactersRange`

**Comment by Deadcows** [comment]
[I just made a comment](https://github.com/Deadcows/MyBox/wiki/Attributes#:~:text=Note%2C%20that%20in%20most%20of%20the%20cases%20attribute%20stacking%20is%20not%20supported%20yet.%0AYou%20may%20try%20to%20mix%20several%20attributes%20on%20the%20same%20field%20and%20check%20if%20it%27s%20working%2C%20but%20further%20work%20is%20required%20to%20fully%20support%20this%20feature.) about this in the docs. 
It will be possible one day but for now it's officially not supported and'll go to my backlog
