### ISSUE TITLE
FindObjectsOfType error

### ISSUE THREAD

**Issue by dinhtai1104** [Deadcows/MyBox#182]
![Screen Shot 2021-11-20 at 00 33 50](https://user-images.githubusercontent.com/51129122/142666246-617bc9a2-ae45-469a-8cc0-3c4b7ddeb8a5.png)
I got a error and idk to fix

**Comment by Deadcows** [comment]
Sorry for late response. [It's fixed](https://github.com/Deadcows/MyBox/commit/8d02ac9d867ccc4400a60e8a3abd523809c211cc)
