### ISSUE TITLE
BUG: OverrideLabel

### ISSUE THREAD

**Issue by HuySora** [Deadcows/MyBox#185]
`[SerializeField, OverrideLabel("SceneReference")] private AssetReferenceT<SceneAsset> editorSceneReference;
`

Expected: Only changing the name
Result:
![image](https://user-images.githubusercontent.com/67303998/155853699-08659ceb-49d7-4603-b133-d8eaed160644.png)

**Comment by Deadcows** [comment]
It is [finally fixed](https://github.com/Deadcows/MyBox/commit/fb3fb53c30233f272a0dfaa050ba638b62d7dae2#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR101)!
