### ISSUE TITLE
Feature request: Fixed collections size in inspector

### ISSUE THREAD

**Issue by HuySora** [Deadcows/MyBox#186]
Remove the ability to add/remove item in inspector (aka fixed)

```cs
[SizeInInspector(4)]
public float[] myFloatArray;

[SizeInInspector(2)]
public List<int> myIntList;
```

![image](https://user-images.githubusercontent.com/67303998/158025894-7ba816bb-e06d-4c37-a3dc-1593cd48c45a.png)

**Comment by Deadcows** [comment]
I'm not sure if it is possible to do 🤔 Unity brings a lot of unfortunate limitations not giving the ability to affect the collection itself with custom attributes and only applying it to the individual elements. 

It is possible to create a collection wrapper with such functionality though. When I need to do some collections with custom functionality, I usually use [ReorderableCollection](https://github.com/Deadcows/MyBox/blob/master/Types/EditorTypes/ReorderableCollection.cs) type, a wrapper for Unity's [ReorderableList](https://github.com/Unity-Technologies/UnityCsReference/blob/50e3fc2c283dccfeee8a09de5f06c5c118c0835d/Editor/Mono/GUI/ReorderableList.cs#L21)
