### ISSUE TITLE
Suggestion : SearchableEnum on enum declaration

### ISSUE THREAD

**Issue by DonTomasDeLaVega** [Deadcows/MyBox#187]
Simply being able to put searchable enum once on an enum you know will get big would be incredible, considering putting SearchableEnum everywhere could be time consuming :)

**Comment by Deadcows** [comment]
It is a very good suggestion! I ran some tests and was tempted to say that it' not possible, cuz unity not works this way.
But yeah, everything is possible 😁 _just need to do it a bit differently_
[It's a great addition](https://github.com/Deadcows/MyBox/commit/584ce92e7507a8bec6e66366c8724fd4c278f5e6), thanks for this idea!

You just need to create your own PropertyDrawer for the Enum, with just a few lines of code. 
Here's the snippet:

	public enum TestEnum {A, B, C, D}
	
	#if UNITY_EDITOR
	[UnityEditor.CustomPropertyDrawer(typeof(TestEnum))] 
	public class TestEnumDrawer : MyBox.EditorTools.SearchableEnumDrawer {}
	#endif

This `SearchableEnumDrawer` base type will do it's things 🙂
