### ISSUE TITLE
Can't use multiple ConditionalField attributes per field

### ISSUE THREAD

**Issue by Tommigun1980** [Deadcows/MyBox#189]
Please ponder the following dummy scenario:

```c#
            public bool matchable;

            [ConditionalField(nameof(SomeClass.matchable))]
            public MatchingData matchingData;

            public bool destructible;

            //[ConditionalField(nameof(SomeClass.matchable))] <-- Problem: can not have multiple attributes per field
            [ConditionalField(nameof(SomeClass.destructible))]
            public DestructionData destructionData;
```

There is a dependency on `destructionData` being drawn only if the entity is matchable and destructible. Right now you can only assign one ConditionalField attribute per field, preventing this from being possible. The visualisation will break if the user first turns on the `matchable` checkbox, then enables the `destructible` checkbox and finally turns off the `matchable` checkbox.

Could support be added for multiple arguments per field?

Thank you!

**Comment by Deadcows** [comment]
Multiple attributes is a long wanted feature, it requires much efforts to implement. 
But I wanted to figure out how to achieve this with one attribute and come up [with this update](https://github.com/Deadcows/MyBox/commit/271aed9694427e560a0d72c445ad6ec28b73cf04)

So now it is possible but with sacrifice of compare values. That'll do for now.
I'll update docs some time later. This is some examples:

		public bool A;
		public bool B;

		[ConditionalField(nameof(A))] 
		public string IsA;
		[ConditionalField(nameof(B), true)] 
		public string NotB;
		[ConditionalField(nameof(A), nameof(B))] // Simply put multiple field names
		public string AandB;
                // To invert some of fields you need to pass two arrays, where prop[0] compared with inverse[0] (if any)
		[ConditionalField(new[] { nameof(A), nameof(B) }, new[] { true })] 
		public string NotAandB;
		[ConditionalField(new[] { nameof(A), nameof(B) }, new[] { false, true })]
		public string AnotB;
		[ConditionalField(new[] { nameof(A), nameof(B) }, new[] { true, true })]
		public string NotAandNotB;

**Comment by Deadcows** [comment]
yep, in your case it'll be `[ConditionalField(nameof(SomeClass.matchable), nameof(SomeClass.destructible))]`
