### ISSUE TITLE
RangedInt inspector breaks multi-object editing

### ISSUE THREAD

**Issue by nipunasudha** [Deadcows/MyBox#19]
For some reason, the newly implemented RangedInt inspector breaks the multi-object editing when multiple instances of a ScriptableObject are selected.

Maybe that's because we are using a FLOAT MinMaxRangeAttribute class for an INT field.

![image](https://user-images.githubusercontent.com/17500323/57312020-620ad700-710a-11e9-9499-5d354e736398.png)

**Comment by Deadcows** [comment]
I'll check this one a bit later, we're crunching towards game demo :) MinMaxRangeAttribute should work fine with int fields, it just round float values to integers... but I never tested it with multi-object selection, I'll figure it out :)

**Comment by Deadcows** [comment]
Fixed in [this commit](Please check this out and let me know if issue with multi-editing remains in some other places with MyBox)
