### ISSUE TITLE
[DisplayInspector] folding

### ISSUE THREAD

**Issue by Tommigun1980** [Deadcows/MyBox#192]
[DisplayInspector] is great, but if you have lots of stuff in your scriptable object you can't really use [DisplayInspector] as the values take up so much space. Would it be possible to add a foldout around the displayed values, possibly with an attribute argument defining whether it should by default be folded in or out?

Also the displayed values don't use their own attribute drawers but I guess that's a Unity limitation that can't be worked around?

Thank you!

**Comment by MianenCZ** [comment]
I've done a workaround for current issues. It is done for automatically assigned values (therefore there is not much need for the field to be visible). But it works for me as a sort of shortcut for our scripters. It saves search time and groups things together. It is used for settings in my case.

I would not use this for fields that have to be assigned manually. It is just too hidden, but for `adjust only` fields it is fine.

Nevertheless, I would prefer an integrated foldout as well.

```cs
[DisplayInspector, Foldout(nameof(Test))]
[SerializeField] public Camera Test;
```
![Capture](https://user-images.githubusercontent.com/45464928/169691104-e219a5fc-6dd1-461e-b83b-060fae3661df.PNG)
![Capture_2](https://user-images.githubusercontent.com/45464928/169691105-a2d71524-a000-4139-87a0-77ae58808ca1.PNG)
![Capture_3](https://user-images.githubusercontent.com/45464928/169691106-6d8f7d87-a3f7-4c14-813c-1d0d7a71aa46.PNG)

**Comment by Deadcows** [comment]
@MianenCZ elegant solution! 
But it is something I wanted to add for a long time, [so here you go](https://github.com/Deadcows/MyBox/commit/ce8ea3d37718e5c955a3e9e85084a80e29d7b5c2)
