### ISSUE TITLE
`ConditionalField` for `FlagEnum` does not support `Everything` value

### ISSUE THREAD

**Issue by MianenCZ** [Deadcows/MyBox#194]
## Summary

I want to create a mode for my custom button. The goal is to show `UnityEvent` GUI for active modes and hide it for inactive ones.

I defined conditions and it worked as expected until `Everything` got selected then all `UnityEvent` GUIs were hidden. 

## Code
```cs

    [System.Flags]
    public enum ButtonVRMode
    {
        Pressed = 0x1,
        Released = 0x2,
        Hold = 0x4,
    }

    public ButtonVRMode ButtonMode = ButtonVRMode.Pressed;

    [ConditionalField(nameof(ButtonMode), false, ButtonVRMode.Pressed)]
    public UnityEvent OnPressed;

    [ConditionalField(nameof(ButtonMode), false, ButtonVRMode.Released)]
    public UnityEvent OnReleased;

    [ConditionalField(nameof(ButtonMode), false, ButtonVRMode.Hold)]
    public float HoldTime;

    [ConditionalField(nameof(ButtonMode), false, ButtonVRMode.Hold)]
    public UnityEvent OnHold;



```

## GUI
![Capture](https://user-images.githubusercontent.com/45464928/169706407-45d5a45e-6a48-48e5-a595-68f260c5da3e.PNG)
![Capture1](https://user-images.githubusercontent.com/45464928/169706408-10d27af4-04c0-4506-9867-38aa0e080c84.PNG)
![Capture2](https://user-images.githubusercontent.com/45464928/169706409-baf454e2-7d72-4422-bd31-ef7f4cd8a115.PNG)
![Capture3](https://user-images.githubusercontent.com/45464928/169706410-6b194bec-59a6-4c4f-8f7a-95f484d825e6.PNG)

## Unity

`Unity 2021.3.1f1 Personal`

## Analysis

I debugged the `ConditionalFieldAttribute` and found out that the `Everything` value is not passed to `propertyValueAsString` as a concatenated string of all enum values but instead as a special value `"-1"`. Also `Nothing` value is passed as a special value `"0"`.

## Suggested solution

File: `ConditionalFieldAttribute.cs`
Class: `ConditionalFieldUtility`
Method: `CompareAgainstValues(string propertyValueAsString, string[] compareAgainst, bool handleFlags)`
Code:

```cs
private static bool CompareAgainstValues(string propertyValueAsString, string[] compareAgainst, bool handleFlags)
{
    if (!handleFlags) return ValueMatches(propertyValueAsString);

    if (propertyValueAsString == "-1") //Handle Everything
        return true;
    if (propertyValueAsString == "0") //Handle Nothing
        return false;

    var separateFlags = propertyValueAsString.Split(',');
	foreach (var flag in separateFlags)
	{
		if (ValueMatches(flag.Trim())) return true;
	}

	return false;

	
	bool ValueMatches(string value)
	{
		foreach (var compare in compareAgainst) if (value == compare) return true;
		return false;
	}
}

```

**Comment by Deadcows** [comment]
Thanks!
