### ISSUE TITLE
IPrepare and prefabs

### ISSUE THREAD

**Issue by Garfounkel** [Deadcows/MyBox#196]
So I have a prefab GameObject with a Monobehavior attached implementing IPrepare. The Prepare function is correctly ran on entering playmode however no changes are kept as prefab overrides because `IPrepareFeature.RunIPrepare` doesn't call `PrefabUtility.RecordPrefabInstancePropertyModifications(myGameobject);` on prefab instances. 

`PrefabUtility.RecordPrefabInstancePropertyModifications(myGameobject);` can be called directly by the user in the `Prepare` function as a workaround. However, it feels like something the user should not have to think about, so maybe it should be part of the `IPrepareFeature.RunIPrepare` logic?

**Comment by Deadcows** [comment]
Good point! Thanks for the detailed suggestion, [it's done](https://github.com/Deadcows/MyBox/commit/3abdf9605887421ba845bc8a4121637f9db74325)
