### ISSUE TITLE
Using two ConditionalFields for two fields.

### ISSUE THREAD

**Issue by ColorTwist** [Deadcows/MyBox#20]
Hello,
Would it be possible to do something like:

 public bool InstantiateLevelPrefab;
 [ConditionalField("InstantiateLevelPrefab",true)]
 public int StartFromLevel = 0;
 [ConditionalField("InstantiateLevelPrefab", false)]
 public GameObject PrefabLevelToDebug;

Like if`InstantiateLevelPrefab`is true show option 1 and if it is false to show option 2.

**Comment by Deadcows** [comment]
Yep, should work just like you wrote it :)

**Comment by ColorTwist** [comment]
I tried it and it shows only 'StartFromLevel' if InstantiateLevelPrefab is set to true :) if it is set to false you see no fields.

**Comment by ColorTwist** [comment]
Yes, old version, now it works!
Great asset, just need to learn how to use more tools :)
Note that when I extracted MyBox files into my project folder I got errors at MyTimeline.cs inside EditorExtensions. I deleted MyTimeLine.cs and it worked.

**Comment by Deadcows** [comment]
Yes, MyBox lacks of documentation on this case. If you using Unity 2019.1 you need to refer to Unity.Timeline package in MyBox.asmdef. If you on 2019.2 you also need to add Unity.ugui reference there
