### ISSUE TITLE
PlayMode startup perfomance issue

### ISSUE THREAD

**Issue by Faimen** [Deadcows/MyBox#206]
Events that are subscribed to launch the game in the editor cause the launch to be delayed by ~15 seconds or more

**Comment by Ludosis** [comment]
I'm noticing after updating from MyBox 1.5 to 1.7 that my time between hitting Play and actually getting into Play Mode has increased drastically. It often now takes me 5 minutes to play. 
MyBox comes up in the progress bar for a long time. 
![image](https://user-images.githubusercontent.com/91435965/181350375-3219b27b-4206-41a1-a6f9-d3c1a6ca9f41.png)

**Comment by ElKevo** [comment]
can you tell me what lines you changed Ludosis?

**Comment by Deadcows** [comment]
yep guys, sorry for that. In the latest version SO check and Prepare on Play are disabled by default as it has to scan the whole project to search for specific types. 
Maybe I'll find some better way in the future, but for now just keep it disabled
