### ISSUE TITLE
Hide inherited properties from inspector

### ISSUE THREAD

**Issue by FredTA** [Deadcows/MyBox#209]
Let's say I have a base class with some serializableField property, that gets inherited by the child class
While the child class _should_ have this property, I don't want this property to be visible in the inspector on this child class. 
It would be awesome if there could be a conditional field where the condition is `className == someClass` or `className != someClass`

**Comment by Deadcows** [comment]
It is already possible. ConditionalField allows to use method to check the field. 
`ConditionalFieldAttribute(bool useMethod, string method, bool inverse = false)` 
so you need to set true in the first parameter and method name in the second

```
[ConditionalField(true, "IsBaseClass")]
public bool ShownInBaseClass;
protected bool IsBaseClass() => GetType() == typeof(MyBaseClass);
```
note the _protected_ keyword. It might be marked _public_ as well, but _provate_ method would not be accessible for the ConditionalField in the child class

..I really need to update the docs 😁
