### ISSUE TITLE
Getting an error when building my own attribute

### ISSUE THREAD

**Issue by carreraSilvio** [Deadcows/MyBox#210]
I'm making a simple folder path attribute. For some reason when I use the OpenFilePanel I keep getting an error from com.domybest.mybox@43a31cbb61/Attributes/FoldoutAttribute.cs:113. 

I'm not using the FoldoutAttribute here. I'm just building my own. It seems to be picking up an event from the EditorUtility.OpenFilePanel ? Any help would be awesome :)

Here is my code:
`
public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
        {
            EditorGUILayout.BeginHorizontal();
            EditorGUILayout.TextField("Value", "test");
            if (GUILayout.Button("...", GUILayout.ExpandWidth(true), GUILayout.Width(30)))
            {
                var result = EditorUtility.OpenFilePanel($"Select folder path", "Assets", "Scripts");
                if (!string.IsNullOrEmpty(result))
                {
                    //do stuff
                }
            }
            EditorGUILayout.EndHorizontal();
        }
`

Here is the error:
![image](https://user-images.githubusercontent.com/3154359/188708345-777ba733-a241-4270-97de-621de0fc87bf.png)

Error attached:
[mybox attr error.txt](https://github.com/Deadcows/MyBox/files/9499684/mybox.attr.error.txt)

**Comment by Deadcows** [comment]
I see the strange issue with Begin/EndHorizontal and things like OpenFilePanel halting gui execution. In this case FoldoutAttribute is catching this exception, but without it you'll see `EndLayoutGroup: BeginLayoutGroup must be called first.`. 
I'm not sure why is this happens, but you may try to call OpenFilePanel outside of layout group like this: 

```
EditorGUILayout.BeginHorizontal();
EditorGUILayout.TextField("Value", "test");
var openSearch = GUILayout.Button("...", GUILayout.ExpandWidth(true), GUILayout.Width(30));
EditorGUILayout.EndHorizontal();
if (openSearch)
{
	var result = EditorUtility.OpenFilePanel($"Select folder path", "Assets", ".cs");
	if (!string.IsNullOrEmpty(result))
	{
		Debug.LogWarning(result);
	}
}
```

sorry for the late response
