### ISSUE TITLE
Spacing for Conditional Attributes

### ISSUE THREAD

**Issue by CaoilainnFW** [Deadcows/MyBox#213]
When multiple sets of variables are hidden under a non-bool enum, the spacing begins to stack slightly, so the variables declared after others appear shifted downwards, and visa-versa.

**Comment by CaoilainnFW** [comment]
Found a fix, in the "GetPropertyHeight" method in the attribute script, instead of returning 0 when "_toShow" is false, return -2, this aligns all the fields properly.

**Comment by Deadcows** [comment]
Thanks! Added this fix to the main branch
