### ISSUE TITLE
Bug: Conditional attributes don't work with list or array

### ISSUE THREAD

**Issue by angelsalascalvo** [Deadcows/MyBox#218]
Hello, I wanted to report that the conditional field does not work for variables of type list or array.
I am using the latest version 1.7.0

    public enum EnumType {
        button,
        fader,
    }
    public EnumType type;

    [ConditionalField(nameof(type), false, EnumType.button)]
    public List<float> positions;

Thank you very much for the utility library!

**Comment by Deadcows** [comment]
This is mentioned in the docs [here ](https://github.com/Deadcows/MyBox/wiki/Attributes#conditionalfield-with-arrays) with a helper type as a workaround.  In your case you should probably do something like this

```
[Serializable]
public class FloatsCollection : CollectionWrapper<float> {}

[ConditionalField(nameof(type), false, EnumType.button)]
public FloatsCollection positions;
```

And access actual points collection with `positions.Value`

**Comment by angelsalascalvo** [comment]
👍 Thanks!
