### ISSUE TITLE
ConditionalFieldAttributeDrawer.cs

### ISSUE THREAD

**Issue by chamx2** [Deadcows/MyBox#22]
Hello I've read your comment in this thread

https://answers.unity.com/questions/192895/hideshow-properties-dynamically-in-inspector.html

Somehow your method is more flexible and when I look for the drawer script it send me to an error 404 since I think you've replaced it with another code or decided to put an all in one solution on GUI Drawer. 

I was wondering what is the script your are using right now for the conditionalfield drawer

Thank you.

**Comment by Deadcows** [comment]
Sure :) Now both editor code and attribute itself is in the same .cs file, [here](https://github.com/Deadcows/MyBox/blob/master/Attributes/ConditionalFieldAttribute.cs)

Look for the parts wrapped with #if UNITY_EDITOR and #endif
The most important stuff is in CheckPropertyVisible method.

CheckBehaviourPropertyVisible() is used by [some other attribute drawer](https://github.com/Deadcows/MyBox/blob/master/Attributes/MustBeAssignedAttribute.cs) so you may just omit that
