### ISSUE TITLE
Bug: Waiting for user code in MyBox.dll to finish executing

### ISSUE THREAD

**Issue by tim-hereijgers-lw** [Deadcows/MyBox#222]
Ever since updating to Unity 2012.3.13f1, I have been experiencing huge load times caused by the MyBox.dll. This happens whenever I start play mode or save something. Below is one of the messages I got, but they also reference other MyBox functions.

![afbeelding](https://user-images.githubusercontent.com/69200724/210334322-c12dfbb4-43e1-4ead-a64d-832a041e8e0d.png)

Using MyBox version 1.7.0

**Comment by tim-hereijgers-lw** [comment]
I've noticed this is a duplicate of #206, but I haven't been able to find a solution for it in that post. It says it's fixed in the latest version, but the problem still persists for me with 1.7.0.

**Comment by Deadcows** [comment]
Did you tried to disable SO processing? 
![image](https://user-images.githubusercontent.com/969858/213984445-c2438db6-78a0-4017-86a6-7816735e7f42.png)

**Comment by tim-hereijgers-lw** [comment]
Hi @Deadcows , that does the trick!
Thank you very much!
