### ISSUE TITLE
Enter Play mode being slower after install the package

### ISSUE THREAD

**Issue by bab202** [Deadcows/MyBox#225]
This package seems very useful with lots of handy attributes but after I import this package my Unity Editor becomes slow, take more time to save scene, more time to enter Play mode. After remove the package, the Editor performance return normal again. I'm using Unity 2021.3.15 LTS Silicon, the version for MacOS M1.

**Comment by erfegon** [comment]
I suggest you to open the MyBox Window found in Tools > MyBox and uncheck everything except Check for Updates.

**Comment by jcs090218** [comment]
Can you lock down which specific component is slow? Or is everything slow? That would help more for debugging. 🤔

**Comment by bab202** [comment]
Not for specific component, after I install this package (into an empty project), I hit Play button in the Editor and I can detect that it takes from 0.5s to 1s slower to start the Play mode. After remove the package, I hit the Play button and Play mode start as fast as normal. I have tried check/uncheck settings in the Menu but result is the same.

**Comment by Deadcows** [comment]
Hopefully it is fixed already, as in the version with the latest commits those three should be disabled by default.
Make sure that in your settings they are also disabled.
Without those features there should be no extra calculations from the MyBox on Playmode

![image](https://github.com/Deadcows/MyBox/assets/969858/7d313691-f552-4a32-93c4-39ad090b9dd2)

**Comment by Deadcows** [comment]
Sorry for the late response 😪 Instant-deadline-mode is finally over for me
