### ISSUE TITLE
Naming Conflit

### ISSUE THREAD

**Issue by Nom-ali** [Deadcows/MyBox#229]
See the Screenshot for details.

I want to use the same name for two fields using ConditionalField, but this naming conflict exists.
Any Solution?
<img width="1342" alt="Screenshot 2023-05-02 at 12 56 48 PM" src="https://user-images.githubusercontent.com/37923691/235615726-dd7d5aeb-54d1-4668-abb6-866cf5eec2ac.png">

**Comment by Deadcows** [comment]
It is not possible to use the same name for two fields with or without ConditionalField 🤔 
What you probably need is one set of unique fields, but with more complex conditions.

`[SerializeField, ConditionalField(nameof(SDK), false, AdsPlatform.Adnob, AdsPlatform.Both)] ` should work just fine, as you may use any number of compare values with ConditionalField.

Yeah, now I see the problem – the docs are outdated and not show this feature.
Sorry for the late response btw 😑
