### ISSUE TITLE
Lerp from RangedFloat/RangeInt

### ISSUE THREAD

**Issue by nipunasudha** [Deadcows/MyBox#23]
I wanted to calculate an intermediate value from a RangeFloat, and I wrote a simple 'Lerp' extension method.

![image](https://user-images.githubusercontent.com/17500323/61332041-e41d2780-a840-11e9-9461-f2400d3cc482.png)

And I thought it would be nice to have this right out of the box! 😁

**Comment by Deadcows** [comment]
Nice idea! I never thought of such usage of Ranged type.
[I added a few more extensions](https://github.com/Deadcows/MyBox/commit/3b6db917db5db3686b5ece8e38da1f1d74ec5f9a) just in case.

Thanks for participation 🤗 If you'll come up with some wild idea for some tools or extensions for MyBox, let me know. I'm eager to improve this lib in all ways 🤠
