### ISSUE TITLE
Editor takes a long time in "MyEditorEvents.OnWillSaveAssets"

### ISSUE THREAD

**Issue by TheXRMonk** [Deadcows/MyBox#230]
I don't know if this is just the Unity loading bar wrongfully blaming Mybox on the loading time, since it doesn't look like the method contains anything that should take a long time?

We're not even using "MustBeAssignedAttributeChecker" or "AutoPropertyHandler", which could be the perpetrators through "OnSave".

**Comment by TheXRMonk** [comment]
Through a bit of digging it seems like the attribute search doesn't use [TypeCache](https://docs.unity3d.com/ScriptReference/TypeCache.GetFieldsWithAttribute.html). Don't know if this is the bottleneck, but since we aren't using AutoProperty or MustBeAssigned, we'll just skip invoking OnSave in MyEditorEvents.

**Comment by CharlieDreemur** [comment]
try to use 
#if UNITY_EDITOR
    using MyBox;
#endif
in every place you use "MyBox" as a temporal solution

**Comment by TheXRMonk** [comment]
> try to use #if UNITY_EDITOR using MyBox; #endif in every place you use "MyBox" as a temporal solution

This is editor issues, so this will do nothing.
