### ISSUE TITLE
Missing def for Attributes/DefinedValuesAttribute.cs

### ISSUE THREAD

**Issue by MarkWangSichun** [Deadcows/MyBox#237]
line 4: using MyBox.EditorTools; 

there is a missing #if UNITY_EDITOR for it. Missing namespace error when making a build.

**Comment by Deadcows** [comment]
Oh, I fell into this trap AGAIN! 😪
Thank you a lot for pointing this out. 
[Fixed](https://github.com/Deadcows/MyBox/commit/e0c4a1a0aee6970c7287b0abb72bde5f1a9204d1)
