### ISSUE TITLE
Conditional UnityEvent inspector is broken

### ISSUE THREAD

**Issue by nipunasudha** [Deadcows/MyBox#24]
My attempt to conditionally show/hide an UnityEvent field failed.
![image](https://user-images.githubusercontent.com/17500323/61573498-5efa7280-aacd-11e9-9092-d235e33c9940.png)

The inspector is broken like this
![image](https://user-images.githubusercontent.com/17500323/61573492-438f6780-aacd-11e9-826a-cce009633cad.png)

**Comment by Deadcows** [comment]
Yep, actually there is no way to draw custom property drawer inside of property drawer. So any property with fancy inspector appearance will be drawn as a plain data :( 

Like with arrays, it's just the way unity works.

**Comment by Deadcows** [comment]
...buuut I found this thread on how to hack the engine to make it done, so maybe there is some hope :)

// I'll check it a bit later
[https://forum.unity.com/threads/drawing-default-property-drawer-in-a-custom-property-drawer.197268/](https://forum.unity.com/threads/drawing-default-property-drawer-in-a-custom-property-drawer.197268/)

**Comment by woistjadefox** [comment]
Works in my case. Is it already fixed?

**Comment by Deadcows** [comment]
Are you sure you checked on UnityEvent? 
Checked it now and it looks like this:

		public bool A;
		[ConditionalField("A")] public UnityEvent B;

![image](https://user-images.githubusercontent.com/969858/72519577-b0ab6c00-3868-11ea-81ad-80fe0a71f8cf.png)

ConditionalField should handle most of the types now, but still struggles with such types like UnityEvent, which have Custom Drawer and base class

**Comment by woistjadefox** [comment]
Yes it's working: 

![image](https://user-images.githubusercontent.com/9056181/72526113-f74b9700-3865-11ea-81df-9c9d89c340a8.png)

![image](https://user-images.githubusercontent.com/9056181/72526090-e569f400-3865-11ea-968e-0c391834d836.png)

I use Untiy 2019.3.0f3 maybe that's the reason why?

**Comment by woistjadefox** [comment]
Ahh.. sorry found out why. I use a custom property drawer for UnityEvents:
https://gist.github.com/ByronMayne/70a46e73f3af7fb9fec7437174dd4858

**Comment by Deadcows** [comment]
Whoa 😲. I never thought of possibility to extend existing custom drawers this way! Maybe I'll contact Bryon to embed this one in MyBox. Thanks for bringing this up 👍 
Quite a few of interesting ideas he's got there btw

**Comment by Deadcows** [comment]
[Finally!](https://github.com/Deadcows/MyBox/commit/077c9207a508dfb37a71f4ff8f579b62ef0b0495#diff-2399625a22bd4bace902d73b13dfd938) Now UnityEvent works with ConditionalAttribute and comes with a few nice improvements! Thanks to the Bryon, almost after half of a year I'm able to close this issue 😁

@woistjadefox, you probably should remove your CollapsableEventDrawer.cs before you'll grab the latest commit of MyBox


![image](https://user-images.githubusercontent.com/969858/72534456-e27ffb00-3887-11ea-986e-4d3c7fc616fc.png)
