### ISSUE TITLE
MyEditorAudio.cs not found.

### ISSUE THREAD

**Issue by NK-Studio** [Deadcows/MyBox#247]
Library\PackageCache\com.domybest.mybox@854df5beeb\Extensions\EditorExtensions\MyEditorAudio.cs(13,27): error CS0246: The type or namespace name 'AudioResource' could not be found (are you missing a using directive or an assembly reference?)

Test Unity Version : 2022.3.17f

**Comment by Deadcows** [comment]
Sorry for that! [It's fixed](https://github.com/Deadcows/MyBox/commit/f3b54077f29cf8ca8ede67c26298b717164164c1)
