### ISSUE TITLE
DefinedValues w. method is null

### ISSUE THREAD

**Issue by Exa644** [Deadcows/MyBox#249]
Using the example;

[DefinedValues(nameof(StringTest))] public string StringSelection;

private string[] StringTest() => new[] { "A", "B", "C" };

results in ArgumentNullExceptionb: Value cannot be null. 
Parameter name: source
(DefinedValuesAttribute l. 80)
Unity 2022.3.9f1

**Comment by Deadcows** [comment]
Interesting! Your example works as intended on my side 🤔
I [just added a safecheck](https://github.com/Deadcows/MyBox/commit/3d78e48008b94b3acc9f9578f63d37ea6e4acef7) to at least not spam the exceptions. 
Apparently, there is some problem with finding the method, or with the acquisition of return values. Can you debug with breakpoint on line 100 and see if the GetMethods result is adequate, or is the result returned with invocation is null?
![image](https://github.com/Deadcows/MyBox/assets/969858/be1c6889-146c-431f-ac5b-dbd2d398dc10)

**Comment by Deadcows** [comment]
Ohhhh I see! I never tested the usage of this attribute within nested serialized types apparently 🙂
It always looked up the method definition in the base serialized type, which is DialogueState in your case.
I [fixed it](https://github.com/Deadcows/MyBox/commit/e56483d404441832a982cca63b3f1b7af3616a7a) for you. Thank you a lot for the report! Helpful one 🙂

The other inconvenience I noticed, is that method results are collected and cached on Inspector initialization. So, if you toggle some state that should affect returning values through the inspector, you'll have to deselect this node and select it again (thus reinitialize the inspector for DialogueState) to see the changes. If this will be a major inconvenience for you, please let me know, it should be relatively easy to fix.
