### ISSUE TITLE
[Feature Request] Integrate mob-sakai/UnityEventDrawerEx instead of CollapsableEventDrawer.cs

### ISSUE THREAD

**Issue by TheXRMonk** [Deadcows/MyBox#256]
Here's incompatible issue: https://github.com/mob-sakai/UnityEventDrawerEx/issues/19

Being able to see runtime listeners is more powerful IMO than foldables. Also, this comes with reorderables.

**Comment by Deadcows** [comment]
Good point! I just made is an optional parameter in MyBoxWindow. Unlike on my screenshot, this checkbox should be enabled in your project by default, you can toggle it off

![image](https://github.com/user-attachments/assets/6ab9b435-e6bf-421f-aa92-f14fd5d6f08b)

**Comment by TheXRMonk** [comment]
Damn that was fast! Thank you so much!
