### ISSUE TITLE
Scene attribute issue

### ISSUE THREAD

**Issue by INFGameDev** [Deadcows/MyBox#258]
scene attribute on string array displays the same value for all elements, changing one element changes all other elements to the same value

**Comment by Deadcows** [comment]
That's weird 🤔 Tried to reproduce, it seems to work fine – 
`[Scene] public string[] scenes;`
![image](https://github.com/user-attachments/assets/2bfdfc0c-38e4-4449-9b85-90fd87fed9d6)

What version of Unity are you using? I'll try to check it there

**Comment by Deadcows** [comment]
Also, I would recommend to use [SceneReference ](https://github.com/Deadcows/MyBox/blob/master/Types/SceneReference.cs) type instead. It is much safer and more powerful, instead of the simple strings

**Comment by INFGameDev** [comment]
https://github.com/user-attachments/assets/9b650a8e-7f5d-4b35-9d93-9d7af19d6bd4


2022.3.16f1

**Comment by INFGameDev** [comment]
also yeah, already opted out for sceneref. i guess it was just nice choosing from a dropdown.

**Comment by Deadcows** [comment]
I [fixed the issue](https://github.com/Deadcows/MyBox/commit/5d4b209418d70f259c2631ec738e80fd7d996bd9). So cool that Unity changed the behavior of the PropertyDrawers in the newer versions, but 2022 and prior the fix should do 👍🏻

**Comment by INFGameDev** [comment]
thanks, much appreciated
