### ISSUE TITLE
Conditional based on not null property

### ISSUE THREAD

**Issue by JRichmond27** [Deadcows/MyBox#26]
Is it possible to use the ConditionalField attribute to only show a field if another field is not null? For example, only show a `quantity` Int field if a `quantityText` GameObject field is not null.

**Comment by Deadcows** [comment]
Well, it was supposed to act like this by default, but somehow I forgot to implement that :D 
I changed ConditionalFieldAttribute a bit. Check out [updated documentation](https://github.com/Deadcows/MyBox/wiki/Attributes#conditionalfield)

**Comment by JRichmond27** [comment]
Perfect, thank you!
