### ISSUE TITLE
Question about MonoBehaviourPool in TODO

### ISSUE THREAD

**Issue by Kaynn-Cahya** [Deadcows/MyBox#30]
(Not really an issue, but rather a question. But posted it here since there is no where else to ask it 😅 )

I recently noticed a `TODO` and wanted to help-out if possible. And then realized there is a `MonoBehaviourPool` in one of the lists.<Br>
May I ask what is that feature about?

**Comment by Deadcows** [comment]
Well it'll be great to get some help with this :)! 

I've got vague idea about some static extension to instantiate GO/MB instances but with pooling features working on background.

Imagine case where you instantiate a bullet like this

var bullet = bulletPrefab.GetPoolable<Bullet>(); // Instantiate or activate inactive instance
...
bullet.DiactivatePoolable();

**Comment by Deadcows** [comment]
I updated TODO by the way, with a few clarifications :)
It's cool to see such activity on MyBox. Thanks for participation!

**Comment by Kaynn-Cahya** [comment]
👍 Interesting idea, I have never thought of an object-pool that makes use of an extension method.<br> Had been using a ObjectPoolManager with singleton for quite some time 😅 
I will try to do this when I am free.

**Comment by Deadcows** [comment]
Cool :) Feel free to update TODO with your ideas. I love challenging stuff 😬
