### ISSUE TITLE
RequireTag attribute

### ISSUE THREAD

**Issue by Kaynn-Cahya** [Deadcows/MyBox#32]
Would be nice if we had a `RequireTag` attribute that functions similar to `RequireComponent` attribute.

Example:

```
    [RequireTag("Enemy")]
    public class Enemy : MonoBehaviour {
    }
```

And if someone tries to attach this component to a game-object that does not have the tag set as `Enemy`, it will log a warn/error in the inspector.

(Could also make a `RequireLayer` attribute too.)

**Comment by Deadcows** [comment]
Finally I'll got a chance to use [TypeCache](https://docs.unity3d.com/2019.2/Documentation/ScriptReference/TypeCache.html) for a performant lookup 😄. And maybe not a RequireTag but something like a ForceTag or AutoTag :)? And it will automatically fix the tag and log a warning if it was changed. Yeah RequireTag will do too actually, cause RequireComponent will automatocally add a component 🙄 

Simply put this attribute and tag will be set automatically. Sounds good :)

**Comment by Deadcows** [comment]
[Done!](https://github.com/Deadcows/MyBox/wiki/Attributes#requiretag-and-requirelayer)

Maybe I'll be able to automate it to work during playmode with instantiated objects but that'll do for now :)

**Comment by Kaynn-Cahya** [comment]
👍 Just saw the new version release few minutes ago;
Exactly what I wanted 🎉 , thanks!

**Comment by Deadcows** [comment]
Oh! I just wanted to ask, how do you track new versions? Github notifications or with MyBox warning? 
I made a system to detect new versions and update MyBox with Tools/MyBox/Update window, but not tested it much. 
Personally I use MyBox as a git submodule in my projects

**Comment by Kaynn-Cahya** [comment]
@Deadcows Mainly with notifications.<br>
> From email; (Github notifies me via email)
> I get pop-up notifications from my email application whenever someone emails me.

Though when I loaded my project with the previous version of MyBox, it does show it in the log.<Br>
(Not as a warning though, but as a simple log)
