### ISSUE TITLE
OptionalMinMax not displaying properly in nested inspector

### ISSUE THREAD

**Issue by Kaynn-Cahya** [Deadcows/MyBox#33]
When `OptionalMinMax` is not serialized directly into the inspector, the display becomes weird:

[Link to image of the weird display](https://i.imgur.com/vrrwKQB.png)

More importantly, the check-boxes becomes uninteractable too. Making it unusable in the inspector. 😓 

The code that I used which made this occur:

```
        [System.Serializable]
        private struct SpawnInterval {
            [SerializeField, Tooltip("The min and max waiting time before an enemy is generated.")]
            private OptionalMinMax minMaxSpawnInterval;

            public float MaxWaitingTime { get => minMaxSpawnInterval.Max;  }

            public float MinWaitingTime { get => minMaxSpawnInterval.Min; }

            public float GenerateWaitingTime() {
                return Random.Range(MinWaitingTime, MaxWaitingTime);
            }
        }

        [SerializeField, Tooltip("The random interval between each enemy spawn"), MustBeAssigned]
        private SpawnInterval enemySpawnInterval;
```

I am guessing that this occurs due to the inspector not having enough horizontal space.<Br>We can probably place the check boxes and the field-boxes in separate horizontal-lines if needed.

**Comment by Deadcows** [comment]
Re-he-heally strange! Seems like EditorGUI.Toggle is not responsive in nested inspector and also have some strange offset. Gladly it all was fixed when I put GUI.Toggle instead. Will commit fixed version in a sec

**Comment by Deadcows** [comment]
So the problem with offset is not fixed... found [this question](https://stackoverflow.com/questions/49790639/indentation-messing-up-nested-property-drawers) about same problem. Will investigate further)

**Comment by Deadcows** [comment]
So, it is indent issue with PropertyDrawers. Fixed with a single line, explained [here](http://answers.unity.com/answers/1661328/view.html)

Good to know about this one to fix this edge case on other drawers! Will add to TODO to check other types with PropertyDrawers in nested inspectors
