### ISSUE TITLE
SetValueOnBuild attribute; Sets to a value when building

### ISSUE THREAD

**Issue by Kaynn-Cahya** [Deadcows/MyBox#34]
Would be nice if it was possible to have an attribute that will automatically set a variable's value when building, like so:

```
// Will be automatically set to false when building.
[SetValueOnBuild(false)]
public bool isGodMode;

//...
```

Would help a lot when creating debugging-related values in the inspector; It removes the need of checking those debug-related values before building the application and publishing.

I saw an answer in the post [here](https://answers.unity.com/questions/495007/editor-script-that-executes-before-build.html) that might help when implementing.

If it is not possible to set the value, then maybe log a warn/error to the user about the value instead?

**Comment by Deadcows** [comment]
The problem I see with this one is that during OnBuild event values will be set on currently loaded behaviors. So if this isGodMode field is on Gameplay scene for instance and you've got MainMenu scene loaded while building this value will not be changed.

As the rule of thumb I'm resetting such values in Awake with Application.isEditor check and most of the times keep such options in the single place where they might be opt out with a single line

**Comment by Deadcows** [comment]
Well it is possible to iterate over all scenes during build and may be to log some warnings i guess 🤔 I'll check this idea later

**Comment by Deadcows** [comment]
I put this one in TODO
