### ISSUE TITLE
Reorderable Colections

### ISSUE THREAD

**Issue by android272** [Deadcows/MyBox#40]
Dose MyBox have the ability to create reorderable lists, arrays, or any other collection I want? I have been trying to create one of these for myself but am having trouble. I found your project very useful and was wondering if you had implemented this sort of system.

![image](https://user-images.githubusercontent.com/5912527/67035740-398afe00-f0e8-11e9-95fc-d742fbdf12ad.png)

I have added your conditional fields with an enum dropdown to an array of type T and it works the way I want it to. But now I would like to use a list<T> where I can simply press a button to add and remove the items as well as reorder them as seen in the image above.

**Comment by Deadcows** [comment]
Well we've got [ReorderableCollection](https://github.com/Deadcows/MyBox/blob/master/Types/EditorTypes/ReorderableCollection.cs), but it's intended to be used from Custom Editors.
Here you may make custom editor for ListReorderTest and create ReorderableCollections for every collection you want to handle them the way you want.

    private ReorderableCollection _reorderableSprites;
    private void OnEnabled() { 
        var sprites = serializedObject.FindProperty(nameof(ListReorderTest.Sprites));
        _reorderableSprites = new ReorderableCollection(stack);
        ... 
    }
    public override void OnInspectorGUI() {
        // Draw all the stuff till the last Sprites array
        _reorderableSprites.Draw(); 
        ... 
    }

Surely in your case it's lots of work and I believe it should be easy to make approach to draw as reorderable collection with a custom type

**Comment by Deadcows** [comment]
But with ReorderableCollection you're able to do a lot of stuff :)! 
For instance, with this example I draw array of InteractiveActions (base type for different actions with different drawers):
				_reorderableItemsStack = new ReorderableCollection(stack);
				_reorderableItemsStack.CustomDrawer += ActionDrawer;
				_reorderableItemsStack.CustomDrawerHeight += ActionHeight;
This way I'm able to do stuff like this
![image](https://user-images.githubusercontent.com/969858/67148125-59672100-f2a4-11e9-83c7-bf94ef9db881.png)

**Comment by Deadcows** [comment]
Ok [I did it](https://github.com/Deadcows/MyBox/commit/ccd9c7791e48981f0172479cc8df5a66ab231d32) 😁. 
You've got ReorderableArray<T> and ReorderableList<T> base classes to create your own collections (it's basically a wrappers for "Collection" property of Array or List type):

		[Serializable]
		public class ReorderableInt : Reorderable<int>
		{
		}

		public ReorderableGameObject GOArray;
		public ReorderableTransformList TransformList;
		public ReorderableInt IntArray;
		... // a few way to access collection
		var firstElement = IntArray[0];
		var lastElement = IntArray.Collection.LastOrDefault();


![image](https://user-images.githubusercontent.com/969858/67150601-4a8f6700-f2c2-11e9-9b85-805d971193a3.png)

**Comment by Deadcows** [comment]
I'll update MyBox version a bit later, when'll be able to fix problem with Updater. 
For now I wrote tiny instruction on easiest way to get the latest version (commit) of the package, so you may do this to get Reorderable type

![image](https://user-images.githubusercontent.com/969858/67150759-7d3a5f00-f2c4-11e9-861c-2b7530ca064d.png)

**Comment by android272** [comment]
This is so awesome! Thank you for getting back to me.
