### ISSUE TITLE
Updates don't work

### ISSUE THREAD

**Issue by android272** [Deadcows/MyBox#41]
I just got the message in my log to update MyBox. So I followed the instructions and the update button no longer seems to work. So I just took the latest commit hash from GitHub and replaced that in my manifest.json in my packages folder.

**Comment by Deadcows** [comment]
Did some error messages appeared when you tried to update? 
Thanks a lot for this report!

**Comment by android272** [comment]
No, nothing happened. I just kept clicking the button and nothing looked like it was loading or anything. Luckily I have another library from GitHub and I knew how to update through the manifest.json by replacing the hash.

**Comment by Deadcows** [comment]
I finally were able to work a bit on this issue. 
If you have the opportunity, could you please check Updater with latest version of MyBox? 
Just go to "Tools/MyBox/Update MyBox" and check that there is no warnings in console 🙄
And please report me if you'll get problems with update process in the future.

I'm also suggesting to check "Tools/MyBox/Check for updates on start" back on to get timely notifications 😬

**Comment by android272** [comment]
What is supposed to happen when I click update? Right now I am getting a log message that says:

````It's time to update MyBox :)! Use "Tools/MyBox/Update window". Current version: MyBox.Internal.MyBoxUpdateWindow+Version, new version: MyBox.Internal.MyBoxUpdateWindow+Version
UnityEngine.Debug:Log(Object)
MyBox.Internal.<CheckOnlineVersionAsync>d__10:MoveNext() (at Library/PackageCache/com.mybox@515c81976c8f984827ed3859324ac1a5d72704e9/Tools/Internal/MyBoxUpdateWindow.cs:106)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()
````

**Comment by Deadcows** [comment]
Oh yeah, I didn't mentioned that) Please update manually and in MyBox Update window see if installed and latest versions matches and there is no warnings. Aaaaand we'll see how things will go when new version will be released 🙄
Easiest way to update is to put "com.mybox": "https://github.com/Deadcows/MyBox.git" in manfest.json and delete local version

**Comment by android272** [comment]
Oh ok. now the update window shows that my current version is 1.2.0 and the latest version is 1.2.0. There are also two buttons now "Update GIT packages" and "Open Git release page".
