### ISSUE TITLE
NullRefException in MyBoxUpdateWindow.cs

### ISSUE THREAD

**Issue by skullthug** [Deadcows/MyBox#42]
I love these tools, and recently just attempted to add them to a project (Unity 2018.3.0f2, via grabbing as a zip off Git) but after putting them in the project I began getting the following error whenever I hit Play in the editor.
This is without me even utilizing any of the MyBox stuff yet in code. Not sure what todo exactly.

NullReferenceException: Object reference not set to an instance of an object
MyBox.Internal.MyBoxUpdateWindow+<CheckOnlineVersionAsync>d__17.MoveNext () (at Assets/Extensions/MyBox/Tools/Internal/MyBoxUpdateWindow.cs:131)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:111)
UnityEngine.UnitySynchronizationContext.Exec () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:72)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:93)

**Comment by Deadcows** [comment]
I'm sorry for inconvenience! :( 
Try to toggle "Tools/MyBox/Check for updates on start" menu item. This should work, and I'll try to refactor Updater a bit and fix this

**Comment by skullthug** [comment]
No worries, thanks for providing these great tools 🍻

**Comment by Deadcows** [comment]
I finally were able to work a bit on this issue. 
If you have the opportunity, could you please check Updater with latest version of MyBox? 
Just go to "Tools/MyBox/Update MyBox" and check that there is no warnings in console 🙄
And please report me if you'll get problems with update process in the future.

I'm also suggesting to check "Tools/MyBox/Check for updates on start" back on to get timely notifications 😬

**Comment by skullthug** [comment]
I apologize for not getting around to testing this as I've switched to
another project, and haven't had the opportunity to re-add MyBox's glorious
helpers. I am a slug and a goon.
I just want you to know I highly highly appreciate the service you provide
with these things.
