### ISSUE TITLE
ConditionalField performance issue

### ISSUE THREAD

**Issue by CarlosPerson** [Deadcows/MyBox#43]
Super useful repo! Thank you for sharing it 👍 

I have been using the ConditionalField attribute and, while very powerful, it is giving me performance issues. Even with the basic "bool" condition mode, if causes significant hiccups on the editor. This happens when when enabling/disabling the target bool OR whenever I interact in any other way with the script. 

Is there anything that could be done to fix it, or at least to limit the lag/hiccup to happen only whenever we enable/disable the bool ? 

Thanks!

**Comment by Deadcows** [comment]
I glad you liked it :)
I didn't spend much time optimizing it, actually. Conditional Field is bulky and slow indeed, I'll see what I can do

**Comment by CarlosPerson** [comment]
Awesome! Looking forward for it!

**Comment by android272** [comment]
I was just about to open an issue about this. When I add just a few ConditinoalFields Unity drags to a halt. I can bearly work on my project.  I thought it had to do with the new Reorderable collections. But I just stripped out the reorderable collections and kept the ConditinoalFields and vice-versa and it is definitely the ConditionalFields the is the problem.

**Comment by Deadcows** [comment]
Sorry for this delay guys, I've got too much work on my project recently. Hopefully I'll be able to check this issue next week

**Comment by Deadcows** [comment]
I made a few optimizations in the [latest commit](https://github.com/Deadcows/MyBox/commit/f1b1df81241aaf469fc6e9b1d8dde927f9670529)

Unfortunately I was unable to reproduce this performance issues so I acted blindly but I changed a lot of stuff to one-time caching so it should help.

Can you please check this out and inform me if it helped or not? 

[Please update manually](https://github.com/Deadcows/MyBox#installation)

**Comment by CarlosPerson** [comment]
It works like a charm! Funny how it was just in time for me, as I was literally creating the PR on my project with the ConditionalFields disabled, as they were unusable. 

Thank you!

**Comment by android272** [comment]
Yes, that worked for me as well. Thanks!
