### ISSUE TITLE
ConditionalField does not interact well with arrays

### ISSUE THREAD

**Issue by CarlosPerson** [Deadcows/MyBox#44]
I am the one that asked for performance improvement on ConditionalField, thanks again for delivering :)

I have found a bug: turns out that if you have an array of elements and you want to conditionally hide some fields, it stops working after the first element. Example:

![VSr0WUw08R](https://user-images.githubusercontent.com/1760653/68608321-da37c800-04b2-11ea-8887-2214be646b13.gif)

In that example, the fields are defined as such:

```
public class CinematicSequence 

(...)

[Separator("Background Music")]
[SerializeField] bool _initialBackgroundMusic;
[ConditionalField("_initialBackgroundMusic")]
[SerializeField] AudioClip _initialBackgroundMusicToPlay;
```

Excellent plugin and excellent developer support so far! Thank you!

**Comment by Deadcows** [comment]
Oh my 🙈 This fields is in the struct and you use ReorderableCollection from MyBox to wrap this struct?

**Comment by CarlosPerson** [comment]
Correct!
```
/// <summary>
/// Sequence list in order of execution
/// </summary>
[Reorderable(null, "Sequence", null)]
[SerializeField] CinematicSequenceList _sequences;
/// <summary>
/// Structure needed by Reorderable Array to allow inspector reordering
/// </summary>
[System.Serializable]
public class CinematicSequenceList : ReorderableArray<CinematicSequence> { }
```

**Comment by Deadcows** [comment]
![image](https://user-images.githubusercontent.com/969858/68663387-9ba41b00-054f-11ea-8768-d741e3d33cfe.png)
aaand with new 19.3 unity ui 😨 
_...rolling up my sleeves_

**Comment by Deadcows** [comment]
Should work fine now with [latest commit](https://github.com/Deadcows/MyBox/commit/18285f7b093758582bca77344e5b8727fcb5bb84)

I'll make separate issue here for this layout problem. Will check it when 19.3 will be out of beta 🙄

**Comment by CarlosPerson** [comment]
Works like a charm, thanks!
