### ISSUE TITLE
Layout issues in 2019.3

### ISSUE THREAD

**Issue by Deadcows** [Deadcows/MyBox#45]
![image](https://user-images.githubusercontent.com/969858/68669035-9ac4b680-055a-11ea-8b2f-d93fb230f9c9.png)

Maybe there is more to find, will check it when 19.3 will be out of beta

**Comment by Kaynn-Cahya** [comment]
Probably a related issue, whereby the name of variable in the inspector does not appear when apply `PositiveValueOnly` attribute.

Shown in this image: https://imgur.com/c1nemAc
(Notice that there is no name on the left hand side.)

Happened after I switched to Unity 2019.3.xfx
Might be happening to other attributes too (?), will report here if I found any that has similar issues.

**Comment by Deadcows** [comment]
> Probably a related issue, whereby the name of variable in the inspector does not appear when applying `PositiveValueOnly` attribute.

Oh my. It's actually shouldn't be related with Unity version. I just.... don't draw label in attribute drawer. I never used this attribute myself and somehow missed this 😳
Thanks for the report, [it's fixed now](https://github.com/Deadcows/MyBox/commit/37b5fcf226876372b080685e682b3a2a5b9dae03)

**Comment by Deadcows** [comment]
btw I'll probably will replace PositiveValueOnlyAttribute with MinValueAttribute and MaxValueAttribute or something. Same functionality but much more flexible

**Comment by Deadcows** [comment]
Drawing issue was related to Reorderable Collections and now it's [fixed](https://github.com/Deadcows/MyBox/commit/37abc8b9a381b4033c36a6a42c6835faba2aed57)
