### ISSUE TITLE
ConditionalFieldTabAttribute

### ISSUE THREAD

**Issue by android272** [Deadcows/MyBox#46]
So I was going to modify your ConditionalFieldAttribute and split it into ConditionalFieldDropDownAttribute and ConditionalFieldTabAttribute and do a pull request but oh my God I have no idea what is going on in that class. I followed this tutorial and got tabs working much like your CinditionalFieldAttribute except it is not an attribute which I would like it to be. I like how your ConditionalFieldAttributes work. Would you be able to implement this?

https://www.youtube.com/watch?v=vAi7-unj1Ww&app=desktop

**Comment by Deadcows** [comment]
Nice idea :)! The most scary part of the code is handling the cases when conditional field have some custom drawer of attribute with custom drawer 😄 Like, 95% of code is workarounds for edge cases.

The actual code is in the ConditionalFieldUtility where we get SerializedProperty of field to check with FindRelativeProperty() and compare it's value against desired values with PropertyIsVisible().

Buuut anyways)
Editor tabs is cool feature and I use it a lot in my custom inspectors. 
I can imagine an attribute, like, 

[FieldTab("First Tab")] public bool A;
[FieldTab("Second Tab")] public bool B;
public bool C;

But when you say "Conditional Tab" what behaviour do you want to achieve?
and at the very top of inspector there will be two tabs and field C is under them...

**Comment by Deadcows** [comment]
Well now I thinking on how to achieve this and it's probably not a trivial task 🙄 
There is probably should be AttributeDrawer to simply return 0 in GetPropertyHeight.
And some another Editor _for all MonoBehaviours_ like with ButtonMethodMonoBehaviourEditor to draw such tabs with fields if there is any and then call base.OnInspectorGUI();

That's the first idea I've got. Yep, I probably should separate the code to draw fields with custom drawers from ConditionalFieldAttribute to use it in other places 🤔

**Comment by android272** [comment]
When I say "Conditional Tab" the behavior I would like to achieve is pretty much the same as how the current conditionalFieldAttrubute works now. Instead of a dropdown that determines what fields show up in the inspector the tabs determine what shows. Thats why I suggested changing conditionalFieldAttrubute into conditionalDropdownAttrubute and then adding a new conditionalTabAttrubute  or something like that. This way people know that these two attributes work similarly.

hmmmm.... I guess after looking at what all the conditionalFieldAttrubute can do tabs may not be like these. Either way bellow is how I would like this to work.

````
[ConditionalTab(nameof(tabEnum), false, Tab.Tab1)] public string stringVar1;
[ConditionalTab(nameof(tabEnum), false, Tab.Tab1)] public int intVar1;
[ConditionalTab(nameof(tabEnum), false, Tab.Tab2)] public string stringVar2;
[ConditionalTab(nameof(tabEnum), false, Tab.Tab2)] public int intVar2;
[ConditionalTab(nameof(tabEnum), false, Tab.Tab3)] public string stringVar3;
[ConditionalTab(nameof(tabEnum), false, Tab.Tab3)] public intVar3;
````

![tab1](https://user-images.githubusercontent.com/5912527/69000542-4fceda00-089f-11ea-8c2d-02f32c77d6ca.PNG)

the other thing to think about is what do you do when there are too many tabs for the inspect.

**Comment by Deadcows** [comment]
Okay, I've got a nice idea on how to make such thing. It might be REALLY helpful 😁 I'll make it when I've got a time. And it might be not in 2019 😰
Beta release is soon you know! CRUNCHING!😅

**Comment by android272** [comment]
Beta release for what? What are you working on?

**Comment by Deadcows** [comment]
Unfortunately there is not much info yet, [that's all we posted online for now](https://www.facebook.com/TheFinalStation/photos/a.349117081913040/1425144610976943/?type=3&theater)
Demo is for publishers, and we will post more info later this year.

Oh I noticed you are Andrew too 😃 What is your project? if you can share the info

**Comment by android272** [comment]
I am just starting out. I am making a Text Adventure after my action RPG failed. I know a text adventure in Unity? Well I know I want to make the RPG in unity so I might as well make this project in Unity to learn game dev and Unity at the same time. I found the link below about ideas for the first projects to make as a new game dev. At first, I was going to blow through it but the more I thought about making a text adventure the more I felt like I really want to make one. So the plan is that the text adventure will act as a lore book for our RPG's. Kinda like reading a witcher book if you want to learn more about the witcher world.

What I am using your library for is, I have a list of roomDescriptions that I can conditionally show and hide the different types of descriptions. RoomDescription, DarkRoomDescription, images etc. Then the game loops through the list and displays the text/images.

http://www.gamefromscratch.com/post/2013/08/01/Just-starting-out-what-games-should-I-make.aspx

**Comment by Deadcows** [comment]
That's cool :) My first attempts in gamedev were oldschool ascii roguelike and zork-like text quest! Not mention RPG Maker experiments as a kid. Good luck with your project

**Comment by android272** [comment]
Yah RPG Maker was amazing as a kid. Thanks man. Good luck with your project as well.

**Comment by Deadcows** [comment]
Hey! Check out the [Foldout Attribute](https://github.com/Deadcows/MyBox/wiki/Attributes#foldout) 😬 Basically it do the things you wanted.
