### ISSUE TITLE
Incompatibility with PixeyeHQ's InspectorFoldoutGroup

### ISSUE THREAD

**Issue by tonygiang** [Deadcows/MyBox#48]
This package is causing [InspectorFoldoutGroup](https://github.com/PixeyeHQ/InspectorFoldoutGroup
) to not have any effect as soon as it is imported. I'm not sure this issue is caused by this package or InspectorFoldoutGroup, I'm just going to bring it up here first and if nothing can be done on this end, I'll bring this issue to InspectorFoldoutGroup repo.

Side note: I think InspectorFoldoutGroup is a good fit within this package. If this issue ever gets resolved, I think you should consider including it.

**Comment by Deadcows** [comment]
Yep, unfortunately ButtonMethodAttribute and this Foldout from Pixeye are both trying to add custom drawer for MonoBehaviours and conflicting on this. Recently I thought on how to make foldout groups actually😮! 
I love Pixeye work and probably will ask him if he's ok if I'll add his solution to MyBox 😏
For now you may comment out line 27 in ButtonMethodAttribute.cs. This will disable ButtonMethod but allow you to use Foldout 😉

**Comment by Deadcows** [comment]
In a few days I'll include InspectorFoldoutGroup by Pixeye in MyBox! Hooray 😄

**Comment by Deadcows** [comment]
[Done!](https://github.com/Deadcows/MyBox/wiki/Attributes#foldout) 🤓
