### ISSUE TITLE
ReorderableColections can not have a ConditionalField attribute.

### ISSUE THREAD

**Issue by android272** [Deadcows/MyBox#51]
Hello I was playing round with the following code when I found out that ReorderableLists can not have the ConditionalField attribute. Bellow is a bit of code that I was trying to use. Yes, I know that I have a ReorderableList inside my ListReorderable. If I comment out the ConditionalField attribute then this will work having a list within a list.

````
[System.Serializable]
public class ReorderableList : ReorderableList<ListReorderable> {}

[System.Serializable]
public class ListReorderable : IHasItems
{
    public DescriptionType type = DescriptionType.Description;

    [ConditionalField(nameof(type), false, DescriptionType.Description)]
    public string description;

    [ConditionalField(nameof(type), false, DescriptionType.Container)]
    public ListReorderable container;
}

public enum ListType { Description, Image, Character, DarkRoom, Item, Switch, Exit, Container }
````

Also, I noticed that the conditional fields within the new list do not appear as they should. Below is an image showing what I am seeing. What I expected was to see a dropdown within the container list that should default to description and have a text area below it just like the RoomDescription list does.

![image](https://user-images.githubusercontent.com/5912527/71315435-4c44ea80-242b-11ea-9141-a6d016837316.png)

**Comment by Deadcows** [comment]
Sorry for the late response 😵 I've got some time to get back to MyBox, finally!

Indeed, Conditionals handled by custom MonoBehaviour editor and ReorderableList simply draws collection items with EditorGUI.PropertyField which is not allows to use custom drawers and such.

ReorderableList simply wraps up my ReorderableCollection (which is wraps up UnityEditorInternal.ReorderableList type😁). It's relatively easy to create custom drawer with ReorderableCollection. [AssetsPresetPreprocessEditor ](https://github.com/Deadcows/MyBox/blob/master/Tools/AssetPresetPreprocessor/AssetsPresetPreprocessEditor.cs#L46) is made this way. 
In my projects I made pretty cool stuff with ReorderableCollections, like this one, with reorderable set of interactive actions. Collection holds base class references and custom editor overrides drawer for each type

![image](https://user-images.githubusercontent.com/969858/80704921-296bc680-8aee-11ea-83e9-220b3604ee04.png)

I probably won't mess with current implementation of ReorderableList for now, but I'll think how to make ReorderableCollection as easy to use as possible
