### ISSUE TITLE
Foldout not working in serialized non-UnityEngine.Object classes

### ISSUE THREAD

**Issue by woistjadefox** [Deadcows/MyBox#52]
The Foldout attribute has no effect in serialized standard classes:
![image](https://user-images.githubusercontent.com/9056181/72527552-4fd06380-3869-11ea-9b0b-d35e54a48710.png)

**Comment by Deadcows** [comment]
I'm not sure it's possible to extend current implementation to work this way but I'll look into this 🙄

**Comment by Tommigun1980** [comment]
Maybe this could be added to the documentation as I was also trying to do exactly this.

**Comment by Deadcows** [comment]
good point! warning about it is added to the docs
