### ISSUE TITLE
MyExtensions.HasComponent<T> arbitrarily has a stricter type constraint than GameObject.GetComponent<T>

### ISSUE THREAD

**Issue by tonygiang** [Deadcows/MyBox#53]
The built-in method `GameObject.GetComponent<T>` has no type constraint to serve a specific use case: To [get all components on a GameObject that are subtypes of an interface passed as T](https://answers.unity.com/questions/60357/getcomponent-and-interfaces.html). The `MyExtensions.HasComponent<T>` method in this package should remove the type constraint so that it can check every type that `GameObject.GetComponent<T>` can get, especially since the current implementation of `MyExtensions.HasComponent<T>` is just
`return gameObject.GetComponent<T>() != null;`

**Comment by Deadcows** [comment]
Thanks for bringing this up! Fixed it in latest commit. I should review my extensions probably :)
