### ISSUE TITLE
Serializable classes declared as fields under the ConditionalField Attribute don't serialize.

### ISSUE THREAD

**Issue by DanErhardt** [Deadcows/MyBox#56]
Hello,
First of all I'd like to thank you for making your scripts available to the public.
It's an amazing series of tools, so useful and sometimes even fun to use.

About the issue, am I doing something wrong or this attribute doesn't support what I'm trying to do?

![Conditional Field Code](https://user-images.githubusercontent.com/51964473/73594807-85737e80-44f0-11ea-8ea4-e74043ce9f7d.png)
![Conditional Field Inspector](https://user-images.githubusercontent.com/51964473/73594808-860c1500-44f0-11ea-8d12-f72f3cb354df.png)

Thank you!

**Comment by Deadcows** [comment]
Thanks for this report. 
It was [pretty easy to fix](https://github.com/Deadcows/MyBox/commit/5e7708a8fbc1aae50076a112eb171ebeeacb42aa) actually😄
