### ISSUE TITLE
Feature Request: MultiConditionalFields

### ISSUE THREAD

**Issue by TheXRMonk** [Deadcows/MyBox#59]
Would be nice to make more complex conditional fields, including AND OR operators. :)
It doesn't seem like this is currently included.

**Comment by Deadcows** [comment]
How cool it would be to have the ability to pass Action into the attribute 🤗 
But I've got some ideas on how to achieve this. Maybe with additional attributes. Or with string parsing, like 

    [ConditionalField(nameof(HostileNPC) + " == true && " + nameof(AttackRange) + " <= 5")]
    public AnimationStateReference MeleeAnimation;

...buuut I'm not sure😁 Maybe you have some ideas on the design of such approach? 
And every time when I'm trying to imagine use-cases for such complex scenarios I come up with REALLY bad architecture design. 
What is your use case for such complex conditions?

**Comment by Deadcows** [comment]
How do you think about ability to use validation function?
Like with the case with MeleeAnimation:

    [ConditionalField("MeleeAnimationFieldShown")]
    public AnimationStateReference MeleeAnimation;

    private bool MeleeAnimationFieldShown() => HostileNPC && (AttackRange <= 5);

I thought about it for a while, but I didn't want to clutter code with such functions. But this is very flexible approach

**Comment by VirsabiMunk** [comment]
This is the usecase (error) I have now:
![conditionalfield use case](https://user-images.githubusercontent.com/54309738/74327757-03574580-4d8d-11ea-9a2b-2e98baf10405.gif)

I'll try your suggestion when I have time :)

**Comment by Deadcows** [comment]
Oh! That would be easier to fix. 
I just need to check if target have its own [ConditionalField] and is visible and hopefully it won't cause any stackoverflows 😅

**Comment by android272** [comment]
I have a use case where I have a dropdown the reveals some fields depending on what is selected. One of these options has some fields that are only needed some of the time so I have them hidden under a checkbox bool... I just realized as I am writing this that I could make the Checkbox only show if I have b selected in the drop-down and what they are hiding show if the box is checked...

Well, I do have another use case where I want some but not all options in the drop-down to have some fields. So something like this.
A - has the field
B - does not
C - has the field
D - has the field

**Comment by VirsabiMunk** [comment]
I noticed [Naughty Attributes](https://github.com/dbrizov/NaughtyAttributes) has a conditional field that can do AND OR operations along with hiding or setting the field to "readonly".  
From their [documentation](https://dbrizov.github.io/na-docs/attributes/meta_attributes/enable_disable_if.html).

They also has some other neat features, but I wouldn't want to decide between this and mybox, so would be cool to integrate some of those into mybox :)

**Comment by Deadcows** [comment]
Wow, some of attributes there are really useful 🤯 And most of them are just like in MyBox 😜
His ShowIf is a bit simpler because his checks based only on bool values, but I've got some ideas 😉
Hes BoxGroup implementation looks cool, I'll consider to update my FoldoutAttribute.


You mentioned InfoBox and I remembered about CommentaryComponent! I completely forgot to write docs on it 😅

![](https://habrastorage.org/webt/7j/nz/wo/7jnzwossqzp6uxe0xfoeoamxob4.gif)

And I wanted to use same functionality to add comments as a fields, not as a components. So this request is WIP

**Comment by Deadcows** [comment]
Now it is possible to have multiple conditions on the same field. Although it's not the final version of the feature it is working 🙂


```
  [ConditionalField(nameof(A))]  public string IsA;
  [ConditionalField(nameof(B), true)]  public string NotB;
  [ConditionalField(nameof(A), nameof(B))]  public string AandB;
  [ConditionalField(new []{nameof(A), nameof(B)}, new []{true})]   public string NotAandB;
  [ConditionalField(new []{nameof(A), nameof(B)}, new []{false, true})]  public string AnotB;
  [ConditionalField(new []{nameof(A), nameof(B)}, new []{true, true})]  public string NotAandNotB;
```

I'll add more info in wiki later. If you got some questions please let me know 😉

**Comment by Tommigun1980** [comment]
Hi @Deadcows!
Is there any way to set up expression where the types that must be checked can not just use the inverse pattern? As an example let's say that queryType must be Option2 and someFlag must true.

These don't work:
`[ConditionalField(new[] { nameof(queryType), nameof(someFlag) }, null, new object[] { QueryType.Option2, true })]`

`[ConditionalField(new[] { nameof(queryType), nameof(someFlag) }, new bool[] { false, true }, new object[] { QueryType.Option2 })]`

`[ConditionalField(new[] { nameof(queryType), nameof(someFlag) }, null, new object[] { QueryType.Option2 }, new object[] { true })]`

How do I combine these? It seems to me that the fix only works when the types can be inverted, no?

Thank you again for a really fantastic project!!

**Comment by Deadcows** [comment]
> Hi @Deadcows! Is there any way to set up expression where the types that must be checked can not just use the inverse pattern? As an example let's say that queryType must be Option2 and someFlag must true.
> 
> These don't work: `[ConditionalField(new[] { nameof(queryType), nameof(someFlag) }, null, new object[] { QueryType.Option2, true })]`
> 
> `[ConditionalField(new[] { nameof(queryType), nameof(someFlag) }, new bool[] { false, true }, new object[] { QueryType.Option2 })]`
> 
> `[ConditionalField(new[] { nameof(queryType), nameof(someFlag) }, null, new object[] { QueryType.Option2 }, new object[] { true })]`
> 
> How do I combine these? It seems to me that the fix only works when the types can be inverted, no?
> 
> Thank you again for a really fantastic project!!

I know it's really confusing to do complex checks. Hopefully, when I'm done with MyBox 2.0 you'll be able to simply put several ConditionalField attributes on top of one field.

But for now..
Actually, it looks like your first attempt _should_ work. At least this quick test works for me

```
public enum MyEnum
{
	A, B, C
}

public MyEnum EnumCondition;
public bool BoolCondition;

[ConditionalField(new[] { nameof(EnumCondition), nameof(BoolCondition) }, null, new object[] { MyEnum.B, true })]
public string WhenB_and_True;
```

Can you please try it again and confirm, that both queryType and someFlag are shown in inspector. And also tell me if tested field is always shown or in contrary is always hidden?
