### ISSUE TITLE
Getting some NullRefferenceExeptions form MyBox and I don't know why

### ISSUE THREAD

**Issue by android272** [Deadcows/MyBox#60]
So I just started getting these NullRefferenceExeptions and I am not exactly sure why. I am not sure when this first started but even after updating I still get these when I run my game. Fortunately, these don't seem to prevent me from playing my game but it is quite annoying to have these errors always in my console while debugging my own code.

NullReferenceException: Object reference not set to an instance of an object
MyBox.Internal.UnityObjectEditor.OnDisable () (at Library/PackageCache/com.mybox@c0a62452d5e378136d87ee7c052906bf370e6fcf/Tools/Internal/UnityObjectEditor.cs:21)

NullReferenceException: Object reference not set to an instance of an object
MyBox.Internal.UnityObjectEditor.OnDisable () (at Library/PackageCache/com.mybox@c0a62452d5e378136d87ee7c052906bf370e6fcf/Tools/Internal/UnityObjectEditor.cs:21)
UnityEditor.AssetDatabase:SaveAssets()
XNodeEditor.NodeEditorWindow:OnFocus() (at Library/PackageCache/com.github.siccity.xnode@7e93ffe4b75a6cab453223d20c5e03f4d7c57f7f/Scripts/Editor/NodeEditorWindow.cs:80)
UnityEditor.DockArea:OnEnable()

**Comment by Deadcows** [comment]
Please check the [latest update](https://github.com/Deadcows/MyBox/commit/e5e7ea8233758b5ccc2eb8fbf9feb07235323bde).
I believe this might happen when domain is unloaded before playmode and some referenced objects (created in OnEnable) are cleared before "OnDisable" method is called and nullref exception appears. I've experienced something like this once, my fix should help
