### ISSUE TITLE
Feature Request: InitializationField

### ISSUE THREAD

**Issue by kard02** [Deadcows/MyBox#64]
It would be nice to have an attribute that makes fields grayed out on runtime (so you can't edit them). I am currently in need of something like that, because code that uses some fields only runs once and it could confuse other people.

**Comment by Deadcows** [comment]
Great idea! I changed ReadOnlyAttribute a bit in [last commit](https://github.com/Deadcows/MyBox/commit/599d6caa17c395ecfb46680923d35b63d9eac3d8)

Now to do the thing you want use [ReadOnly(true)]

**Comment by Deadcows** [comment]
well... now I'm not too sure if naming is clear enough. InitializationField will work better, how do you think?

**Comment by kard02** [comment]
> well... now I'm not too sure if naming is clear enough. InitializationField will work better, how do you think?

The name is a little confusing now, maybe creating seperate class is a better idea.
Btw, I think grayed out functionality could be also useful (when enabled) for the ConditionalFieldAttribute (when the condition is false).

**Comment by Deadcows** [comment]
Sorry for the late response, now I finally got some time to mess up with MyBox 😃

[InitializationFieldAttribute is here](https://github.com/Deadcows/MyBox/commit/fd40e688504294dfc4d0166934fbc38dab0da2b1)!
Also ReadOnly is simply read-only as it was before 🥴
