### ISSUE TITLE
It's impossible to create empty folder within unity

### ISSUE THREAD

**Issue by Deadcows** [Deadcows/MyBox#65]

**Comment by tonygiang** [comment]
Isn't this issue caused by the fact that "CLear empty directories on save" setting is enabled by default?

**Comment by Deadcows** [comment]
It is. I just didn't noticed that Save event occurs when new folder created. Should be easy to fix, when I've got a bit more time :)

**Comment by Deadcows** [comment]
[Fixed](https://github.com/Deadcows/MyBox/commit/30c93c4802299f87b82671874a71d29bfb2ba4ae), finally!
