### ISSUE TITLE
Colors on Conditional Fields don't work or crash Unity

### ISSUE THREAD

**Issue by pedromgdo** [Deadcows/MyBox#67]
When picking a color on conditional fields, it does not save the color picked, or if you try to use the color picker, unity freezes and a restart is required.
Unity version: 2019.3.09f
Code Snippet:
`
    public bool overrideColor = false;
    public bool overrideAlpha = true;
    [ConditionalField("overrideColor")] public Color newColor;
`

**Comment by Deadcows** [comment]
Sorry for the late response.
I'm unable to reproduce the issue 🙄 Can you please check with an empty project?
Also, did you use Conditional Field with some other types? All was fine with them?

**Comment by Deadcows** [comment]
I'll close it for now, will reopen if needed
