### ISSUE TITLE
Reordable lists with [DisplayInspector]

### ISSUE THREAD

**Issue by VirsabiMunk** [Deadcows/MyBox#68]
Would be awesome! Any ideas on feasibility?

**Comment by Deadcows** [comment]
I'm trying to imagine proper use-case for such feature 🙄 
Usually I use DisplayInspector to show SO with some settings, like EnemyStats SO to share specific set of settings across one type of enemies. 
How do you use it?

**Comment by VirsabiMunk** [comment]
> How do you use it?
Similarily to you. My current use case is for a Splash screen system. Using SO's for different types of splashscreens and want to quickly be able to see all the properties of the individual splash screens while also reordering the sequence they are shown in.

**Comment by Deadcows** [comment]
Nice idea! 
Well, I figured out that it's already possible.
You just need to add some wrapper for your SO with DisplayInspectorAttribute

```
[Serializable] public class ReorderableSmartTiles : Reorderable<SmartTileReference> { }

[Serializable]
public struct SmartTileReference
{
	[DisplayInspector] public SmartTile Tile;
}
```

So it works as intended, but there is a issue with this "Element 0", "Element 1" thing drawing in the wrong place, I'll check how to fix this

![image](https://user-images.githubusercontent.com/969858/80679804-4a202600-8ac6-11ea-8f10-93cc28af232b.png)

**Comment by Deadcows** [comment]
Okay, this issue is [finally fixed](https://github.com/Deadcows/MyBox/commit/37abc8b9a381b4033c36a6a42c6835faba2aed57)! 


![image](https://user-images.githubusercontent.com/969858/80687897-a9d0fe00-8ad3-11ea-8829-4421a0974052.png)
