### ISSUE TITLE
Request: [ButtonMethod] through [DisplayInspector]

### ISSUE THREAD

**Issue by VirsabiMunk** [Deadcows/MyBox#69]
Sorry for adding to last week's solved issue ;) 
Button methods would be nice to have accessible through display inspector.
Use case is similar to the reordable list of splash screen SOs. If I were able to see button methods I could initialize/update objects or delete whole screens from the list. 👍

(I really love [DisplayInspetor] - so easy and powerful)

**Comment by Deadcows** [comment]
Yeah, I love DisplayInspetor too 😀
I felt like it'd be cool to have custom buttons in displayed inspector, but I always found ways around it.
But I never used it with collection of types with DisplayInspetor, it makes perfect sense🤓

**Comment by Deadcows** [comment]
[Done! ](https://github.com/Deadcows/MyBox/commit/659640632170bda92a19c6159cf89b384fb55cea)

![image](https://user-images.githubusercontent.com/969858/81173826-582fe400-8fa9-11ea-9fc7-e25d3c9f023c.png)
