### ISSUE TITLE
[Bug] Assembly Reference error on build in MyCursor

### ISSUE THREAD

**Issue by VirsabiMunk** [Deadcows/MyBox#70]
I have made my own internal repo for some tools that relies on MyBox .asmdef.

When building I get an assembly ref error:

`Types\MyCursor.cs(2,13): error CS0234: The type or namespace name 'EditorTools' does not exist in the namespace 'MyBox' (are you missing an assembly reference?)`

Looks like all we need is;
```
#if UNITY_EDITOR
using MyBox.EditorTools;
#endif
```

It's a good idea to split up editor and runtime asmdef's to avoid this :)

**Comment by Deadcows** [comment]
Oh no, not again
...
Thanks Mathias, it's [fixed](https://github.com/Deadcows/MyBox/commit/ba840da2957574e0cad4835177663804ae769e1e)
