### ISSUE TITLE
ReorderableList showing element name in odd locations

### ISSUE THREAD

**Issue by android272** [Deadcows/MyBox#71]
I have been seeing this string in odd places and I finally figured out what it is. Before the text was covered a bit but now I can read that it says the "element #" of the list. Do you know if this has to do with your ReorderableList or is it a Unity thing?

![image](https://user-images.githubusercontent.com/5912527/81199629-e9df2780-8f90-11ea-9fe7-dd105cef3aa6.png)

**Comment by Deadcows** [comment]
This one was fixed a few days ago. Hopefully you'll be able to use latest version soon, when I'll fix ConditionalField problem 👍🏻

**Comment by Deadcows** [comment]
Please let me know if this issue is present in the latest commits. Should be fine after [this one](https://github.com/Deadcows/MyBox/commit/37abc8b9a381b4033c36a6a42c6835faba2aed57) dated April 30

**Comment by android272** [comment]
Yes, it looks like this was fixed for me. Sorry for the late response.
