### ISSUE TITLE
 error CS0246 during build

### ISSUE THREAD

**Issue by VirsabiMunk** [Deadcows/MyBox#73]
Error CS0246: The type or namespace name 'CollectionWrapperBase' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Deadcows** [comment]
Oh my. I should make some check-list with "BUILD DAT THING BEFORE COMMIT" in it😕
[Fixed ](https://github.com/Deadcows/MyBox/commit/1a1da94f7e7cf49b2d213bf1fba74add5e512e53)
