### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by KumoKyaku** [Deadcows/MyBox#74]
![企业微信截图_15898654104958](https://user-images.githubusercontent.com/15962980/82287592-1a808180-99d3-11ea-90df-f26424c0c646.png)

**Comment by KumoKyaku** [comment]
![企业微信截图_15898603658073](https://user-images.githubusercontent.com/15962980/82287624-2f5d1500-99d3-11ea-8dcf-97bb2c0efdbb.png)

**Comment by VirsabiMunk** [comment]
[Dublicate](https://github.com/Deadcows/MyBox/issues/73)
