### ISSUE TITLE
Feature request: Add LoadSceneAsync to SceneReference

### ISSUE THREAD

**Issue by tonygiang** [Deadcows/MyBox#75]
`SceneReference` is a convenient helper type, but it's missing the async loading mode provided by `SceneManager`. Since the existing LoadScene method is just a wrapper around `SceneManager.LoadScene`, a `SceneReference.LoadSceneAsync` method should be pretty simple like:

```
public AsyncOperation LoadSceneAsync(LoadSceneMode mode = LoadSceneMode.Single)
{
    ValidateScene();
    return SceneManager.LoadSceneAsync(SceneName, mode);
}
```

**Comment by Deadcows** [comment]
Good point! [Done](https://github.com/Deadcows/MyBox/commit/ee9546ca741667027149fb4b832899b78fcb5952?w=1)
