### ISSUE TITLE
Image.SetAlpha extension method is too specific to Image type, should be Graphic.SetAlpha 

### ISSUE THREAD

**Issue by tonygiang** [Deadcows/MyBox#76]
`Image.color` is not specifically a property of the Image type, but rather an inherited property from `Graphic`: https://docs.unity3d.com/Packages/com.unity.ugui@1.0/api/UnityEngine.UI.Graphic.html

By targeting `Graphic` type, this extension method would be usable for several types other than `Image`, such as `TextMeshProUGUI`.

**Comment by Deadcows** [comment]
As a solo dev I'm lacking of a code review sometimes 🤓
There's a lot of tiny things to fix I bet.
I'm very glad to have such issues appeared from time to time, thanks 🤠
[Done](https://github.com/Deadcows/MyBox/commit/2c528c81aced53ec1fabc7c09919ee2f0347a7b5)
