### ISSUE TITLE
DisplayInspector with reoderable array?

### ISSUE THREAD

**Issue by carreraSilvio** [Deadcows/MyBox#77]
Is there any way to make these two work together? I have an array of scriptable object. I'm using DisplayInspector to edit the data of each scriptable object. I'd like to be able to reorder them as well. Is that a possibility? :)

**Comment by Deadcows** [comment]
Yep it's doable, but you need to create wrapper class to hold field of your SO, with [DisplayInspector] on the field 🤓

```
public class Test : MonoBehaviour
{
	public ReorderableTestSOWrapper Collection;
}

[Serializable]
public class ReorderableTestSOWrapper : Reorderable<TestSOWrapper> {}

[Serializable]
public class TestSOWrapper
{
	[DisplayInspector]
	public TestSO TestSO;
}

[CreateAssetMenu]
public class TestSO : ScriptableObject
{
	public int A = 2;
	[ReadOnly] public int MulA = 1;

	[ButtonMethod] private void Mul() => MulA *= A;
	[ButtonMethod] private void Res() => MulA = 1;
}
```


![image](https://user-images.githubusercontent.com/969858/83167537-f894a680-a118-11ea-9d3e-95aa28d240d1.png)

**Comment by carreraSilvio** [comment]
Awesome, thanks for the example as well!

**Comment by carreraSilvio** [comment]
@Deadcows  Is there any way to call your add method via script?

**Comment by Deadcows** [comment]
Reorderable is a wrapper for an array. Use ReorderableList<> as a base class and use "Collection" field as regular list

**Comment by Deadcows** [comment]
Well you may manipulate an array as well with Array.Resize... If you want to change your collection during edit-time don't forget to mark it [dirty](https://docs.unity3d.com/ScriptReference/EditorUtility.SetDirty.html) or [record your changes](https://docs.unity3d.com/ScriptReference/Undo.RecordObject.html) 👌

**Comment by carreraSilvio** [comment]
True, true! Thanks for the fast reply. Is there a way to override what your (+) button does on the list?

**Comment by Deadcows** [comment]
Oh that's what you were asking! Well, no, not directly, but Reorderable type is just a wrapper for "ReorderableCollection" type and it's very flexible by itself. You may create your own propertydrawer that uses [ReorderableCollection](https://github.com/Deadcows/MyBox/blob/master/Types/EditorTypes/ReorderableCollection.cs#L57). Look how [ReorderableDrawer works](https://github.com/Deadcows/MyBox/blob/master/Types/Reorderable.cs#L80), you may simply copy that code and extend it a bit. It allows show or hide plus/minus signs, add custom logic to it, add custom drawers per item etc.
The only place where it used in MyBox is [AssetsPresetPreprocessEditor](https://github.com/Deadcows/MyBox/blob/master/Tools/AssetPresetPreprocessor/AssetsPresetPreprocessEditor.cs#L47)

That what I did with ReorderableCollection in my current project
![](https://habrastorage.org/webt/zv/l0/d0/zvl0d033clbbrrk6cskyms-ktus.gif)

btw what logic you want to set to plus button?

**Comment by carreraSilvio** [comment]
I have this state machine with scriptable object that I'm using. I wanted to use your redorederable list and use the add button to choose which Command you want to add. Kind of similar to the gif you sent me.
