### ISSUE TITLE
Conditional field doesn't work with array and list

### ISSUE THREAD

**Issue by Kryloth** [Deadcows/MyBox#80]
Hello, i'm not sure if this is a bug or simply hasn't been implemented yet but
when I use conditional field with an array or a list variable, it doesn't work 
`public bool testBool;`
`[ConditionalField(nameof(testBool))]public List<string> testList = new List<string>();`
`[ConditionalField(nameof(testBool))]public string[] testArray;`
![Screenshot_678](https://user-images.githubusercontent.com/32011762/83218122-8d3de980-a197-11ea-88a9-dfb39f1a1cbd.png)

![Screenshot_677](https://user-images.githubusercontent.com/32011762/83218124-8f07ad00-a197-11ea-9f84-87e5be02c007.png)

Maybe you could make it work with conditional field too

**Comment by Deadcows** [comment]
In one of the latest versions of MyBox I added CollectionWrapper class. 
Example of it is [here](https://github.com/Deadcows/MyBox/wiki/Attributes#conditionalfield) 
![image](https://user-images.githubusercontent.com/969858/83255264-c20e6880-a1b8-11ea-9be9-fd305510f257.png)
