### ISSUE TITLE
Is it possible to have SearchableEnum with ConditionalField?

### ISSUE THREAD

**Issue by carreraSilvio** [Deadcows/MyBox#81]
```c#
public bool testCondition;
[ConditionalField(nameof(testCondition)), SearchableEnum]
public TestEnum searchableEnum;
```

When I try this code up here I get the conditional working, but the searchable enum does not work. I get a warning on the console saying the field "searchableEnum" can't be found. Is there any workaround for this?

**Comment by Deadcows** [comment]
![](https://habrastorage.org/webt/rt/vg/sd/rtvgsdh_vw05z0hrw5jdvh2e8a8.gif)

It works fine for me, but with some warnings... I'll see what causing this, maybe it'll help.

Can you please check that SearchableEnum without ConditionalField works fine for you

Can you provide stack trace of the exception as well please?

**Comment by carreraSilvio** [comment]
Yeah, it is working by itself. I was using the isolated roboryan version before and recently switched to yours to use with the conditional field. 

When using it alone this is what I get:
![4](https://user-images.githubusercontent.com/3154359/83301696-140aba80-a1c8-11ea-8c92-16d3420586e5.gif)


![ss1](https://user-images.githubusercontent.com/3154359/83301721-1bca5f00-a1c8-11ea-9f8f-1adf84508392.png)

When using it with a conditional field:

![3](https://user-images.githubusercontent.com/3154359/83301653-03f2db00-a1c8-11ea-9ea5-0153aa7cfd8b.gif)
Log file:
[Editor.log](https://github.com/Deadcows/MyBox/files/4704120/Editor.log)

**Comment by carreraSilvio** [comment]
OK! So I was able to figure out the issue. I had one CustomEditor script that I had commented out. It was still inside a Editor folder. Simply uncommenting or removing the script entirely solved the issue.
