### ISSUE TITLE
Feature request: CharacterRange attribute

### ISSUE THREAD

**Issue by tonygiang** [Deadcows/MyBox#82]
One of the projects I'm working on is dealing with really big numbers, as in `System.Numerics.BigInteger` and a custom big decimal type. To represent both types' values on Unity Inspector, I use a string type. They would be parsed by the big number types at runtime. I thought it would be nice to have a way to enforce these string fields to only accept number characters so that the string field I use to parse into actual big number type is always guaranteed to be parsable.

But then I thought it would be more general-purpose to have an attribute that limits the range of acceptable characters to ones contained in an argument.

For example, this field:

`[CharacterRange("1234567890.")] public string GrossValue = string.Empty;`

would only accept number characters plus a decimal point.

Or `[CharacterRange("1234567890abcdefABCDEF")]` will enforce a hex-value only field.

Is this possible?

**Comment by Deadcows** [comment]
Oh, nice idea! I think it's be even better to have regex validator attribute

**Comment by Deadcows** [comment]
@tonygiang Thanks for your contributions!
