### ISSUE TITLE
Singleton and MonoSingleton doco

### ISSUE THREAD

**Issue by kirpit** [Deadcows/MyBox#85]
Hi,

I tried to use `Singleton` and `MonoSingleton` classes in my project, instead of bringing new code from outside. As a inexperienced C# developer, I couldn't understand the internals, implementation best practice and `Singleton` relationship with `MonoBehaviour` etc. 

Can someone help me add some wiki examples to these two?

**Comment by Deadcows** [comment]
oh my, sorry for late response! 

ugh.. personally I don't like current implementations of Singleton and MonoBehaviour. I probably will change it for a better version some day.

Singleton class is a way to cache any MB on scene and access it globally. 
So it's just a wrapper to call heavy FindObjectOfType just once.
For example you have object with GameManager monobehaviour on scene, so simply access in from anywhere with 
`Singleton<GameManager>.Instance`.


It's pretty easy to create your own implementation by hand

```
public static GameManager Instance
{
	get
	{			
		if (_instance == null) _instance = FindObjectOfType<GameManager>();
		if (_instance == null)
		{
			var instance = new GameObject("Game Manager");
			_instance = instance.AddComponent<GameManager>();
		}
		return _instance;
	}
}
private static GameManager _instance;

private void Awake()
{
	if (_instance != null && _instance != this)
	{
		DestroyImmediate(gameObject);
		return;
	}

	_instance = this;
	DontDestroyOnLoad(gameObject);
}
```

This way you'll ensure that you have only one (the first loaded) instance and it won't be destroyed when scene is unloaded, it'll be accessible via `GameManager.Instance`

**Comment by Deadcows** [comment]
Also I got only one access point in my previous game to get all needed singletons, found the code :)

```
public static SceneControlManager SceneManager
{
	get
	{
		if (_sceneManager == null)
			_sceneManager = Singleton<SceneControlManager>.Instance;
		return _sceneManager;
	}
	private set => _sceneManager = value;
}
private static SceneControlManager _sceneManager;


public static SavegameManager Savegame
{
	get
	{
		if (_savegameManager == null)
			_savegameManager = Singleton<SavegameManager>.Instance;
		return _savegameManager;
	}
	private set => _savegameManager = value;
}
private static SavegameManager _savegameManager;


public static GlobalReferences References
{
	get
	{
		if (_references == null)
			_references = Singleton<GlobalReferences>.Instance;
		return _references;
	}
	private set => _references = value;
}
private static GlobalReferences _references;


public static AudioManager Audio
{
	get
	{
		if (_audio == null)
			_audio = Singleton<AudioManager>.Instance;
		return _audio;
	}
	private set => _audio = value;
}
private static AudioManager _audio;

...
```

and cached all the stuff in Awake of GameManager:

```
Interface = GetComponentInChildren<InterfaceManager>();
Input = GetComponentInChildren<CustomInputManager>();
Dialog = GetComponentInChildren<DialogManager>();
Effects = GetComponentInChildren<EffectsManager>();
Audio = GetComponentInChildren<AudioManager>();
Savegame = GetComponentInChildren<SavegameManager>();
SceneManager = GetComponentInChildren<SceneControlManager>();
Items = GetComponentInChildren<ItemsManager>();
References = GetComponentInChildren<GlobalReferences>()
```

..yeah. And access was simple as `GameManager.Audio.Play()` and such

**Comment by Deadcows** [comment]
hope this was helpful 🤓 I'll update Singleton later with a better universal solution
