### ISSUE TITLE
Request: Don't have "Clear empty Directories On Save" as true for default install 

### ISSUE THREAD

**Issue by VirsabiMunk** [Deadcows/MyBox#87]
It can lead to a very obscure debug journey. :(

(We have a tool that creates our standardized project structure for when creating a new project - this creates a lot of empty directories).

**Comment by Deadcows** [comment]
Oh my, sorry for that. You're absolutely right, now it's [disabled by default](https://github.com/Deadcows/MyBox/commit/2f3aa81b6446582fbe5fa4706acc86ed6d385287)

I wanted to create some sort of Welcome Window to allow to select desired features when MyBox is imported, but it's still in my TODO
