### ISSUE TITLE
Does not seem to work in Objects are not Monobehaviours

### ISSUE THREAD

**Issue by lejbruce** [Deadcows/MyBox#89]
I wanted to use it help organize my variables within objects that do not inherit from monobehaviour, but instead are references inside my other scripts, but the tags do not seem to work. The Unity ones work, but not the ones from this package.

**Comment by Deadcows** [comment]
Which attributes you'd like to use? Most of the attributes checked at first level of MB because it'll be too heavy to check all the fields recursively inside of MB, but I'll see what I can do

**Comment by Deadcows** [comment]
One guy asked me about that by email so I'll just paste my answer for the future
