### ISSUE TITLE
WarningPool internal usage breaks build

### ISSUE THREAD

**Issue by bakatrouble** [Deadcows/MyBox#90]
At least the following line: https://github.com/Deadcows/MyBox/blob/master/Types/UIFollow.cs#L69 uses `WarningPool` which is not being compiled due to `#if UNITY_EDITOR` directive.

**Comment by Deadcows** [comment]
Oh my, I did it again 😩
[Fixed](https://github.com/Deadcows/MyBox/commit/0672f5bd51da7bf79ff2a17bdb45b4fdeb9f8403)
