### ISSUE TITLE
Turn off "AutoSave on Play" and "Clear Empty Directories on Save"

### ISSUE THREAD

**Issue by MikkelVirsabi** [Deadcows/MyBox#93]
When adding MyBox to a new project these options more often than not cause intended behavior. AutoSave on play from my experience is nice to have switched on only in certain scenarios when you are working on something that is prone to crashing, but most of the time this is not the case, and I find it annoying that it overrides a scene with experimental changes that I did not intend to save. "Clear Empty Directories on Save" sometimes deletes folders that you just created. Therefore it should also be off by default.

**Comment by Deadcows** [comment]
Agree. Such features requires some introduction to the users. Cleanup feature was disabled a few days ago, now I [disabled autosave too](https://github.com/Deadcows/MyBox/commit/75b50ce00cbd77cdd81e9da558399685e462e6c7). Thanks!
