### ISSUE TITLE
OpenUPM build issue with version 1.5.0

### ISSUE THREAD

**Issue by tonygiang** [Deadcows/MyBox#94]
This package is showing a build issue with version 1.5.0 on [OpenUPM](https://openupm.com/packages/com.mybox/), causing the OpenUPM unable to upgrade MyBox to 1.5.0. Please investigate this issue.

**Comment by Deadcows** [comment]
oh my, I never tried to use OpenUPM actually 😑 Now it's the perfect time to dig into it I guess

**Comment by Deadcows** [comment]
Issue is fixed! Thanks for the report
